# Generated by Plain 0.52.2 on 2025-07-08 01:19

import uuid

import plain.flags.models
from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("uuid", migrations.UUIDField(default=uuid.uuid4)),
                ("created_at", migrations.DateTimeField(auto_now_add=True)),
                ("updated_at", migrations.DateTimeField(auto_now=True)),
                (
                    "name",
                    migrations.CharField(
                        max_length=255,
                        validators=[plain.flags.models.validate_flag_name],
                    ),
                ),
                ("description", migrations.TextField(required=False)),
                ("enabled", migrations.BooleanField(default=True)),
                ("used_at", migrations.DateTimeField(allow_null=True, required=False)),
            ],
        ),
        migrations.CreateModel(
            name="FlagResult",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("uuid", migrations.UUIDField(default=uuid.uuid4)),
                ("created_at", migrations.DateTimeField(auto_now_add=True)),
                ("updated_at", migrations.DateTimeField(auto_now=True)),
                ("key", migrations.CharField(max_length=255)),
                ("value", migrations.JSONField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=migrations.UniqueConstraint(
                fields=("name",), name="plainflags_flag_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=migrations.UniqueConstraint(
                fields=("uuid",), name="plainflags_flag_unique_uuid"
            ),
        ),
        migrations.AddField(
            model_name="flagresult",
            name="flag",
            field=migrations.ForeignKey(
                on_delete=migrations.CASCADE, to="plainflags.flag"
            ),
        ),
        migrations.AddConstraint(
            model_name="flagresult",
            constraint=migrations.UniqueConstraint(
                fields=("flag", "key"), name="plainflags_flagresult_unique_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="flagresult",
            constraint=migrations.UniqueConstraint(
                fields=("uuid",), name="plainflags_flagresult_unique_uuid"
            ),
        ),
    ]
