# Generated by Plain 0.3.0 on 2024-08-16 16:46

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainflags", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flagresult",
            constraint=models.UniqueConstraint(
                fields=("flag", "key"), name="unique_flag_result_key"
            ),
        ),
    ]
