# Generated by Plain 0.68.1 on 2025-09-26 18:32

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainflags", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flag",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="flagresult",
            name="uuid",
        ),
    ]
