# Generated by Plain 0.68.1 on 2025-09-26 18:32

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainflags", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flag",
            name="plainflags_flag_unique_uuid",
        ),
        migrations.RemoveConstraint(
            model_name="flagresult",
            name="plainflags_flagresult_unique_uuid",
        ),
        migrations.RemoveField(
            model_name="flag",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="flagresult",
            name="uuid",
        ),
    ]
