# Generated by Plain 0.127.2 on 2026-03-25 16:53

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainflags", "0002_remove_flag_plainflags_flag_unique_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagresult",
            name="flag",
            field=postgres.ForeignKeyField(
                db_index=False,
                on_delete=plain.postgres.deletion.CASCADE,
                to="plainflags.flag",
            ),
        ),
    ]
