# Generated by Plain 5.0.dev20231229213240 on 2023-12-29 22:04

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainqueue", "0005_remove_jobresult_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobresult",
            old_name="completed_at",
            new_name="ended_at",
        ),
    ]
