# Generated by Plain 5.0.dev20240109225803 on 2024-01-09 23:17

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainqueue", "0009_alter_jobresult_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobresult",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("PROCESSING", "Processing"),
                    ("SUCCESSFUL", "Successful"),
                    ("ERRORED", "Errored"),
                    ("LOST", "Lost"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
    ]
