# Generated by Plain 5.0.dev20240114170303 on 2024-01-17 18:45

import uuid

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainworker", "0011_jobrequest_retries_jobrequest_retry_attempt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(required=False, allow_null=True),
                ),
                ("job_request_uuid", models.UUIDField()),
                ("job_class", models.CharField(max_length=255)),
                ("parameters", models.JSONField(required=False, allow_null=True)),
                ("priority", models.IntegerField(default=0)),
                ("source", models.TextField(required=False)),
                ("retries", models.IntegerField(default=0)),
                ("retry_attempt", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="jobresult",
            name="job_uuid",
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESSFUL", "Successful"),
                    ("ERRORED", "Errored"),
                    ("LOST", "Lost"),
                ],
                max_length=20,
            ),
        ),
    ]
