# Generated by Plain 5.0.dev20240117193239 on 2024-01-17 19:41

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainworker", "0013_alter_job_options_alter_jobresult_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="unique_key",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobrequest",
            name="unique_key",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="unique_key",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_class", "unique_key"], name="job_class_unique_key"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["job_class", "unique_key"], name="job_request_class_unique_key"
            ),
        ),
    ]
