# Generated by Plain 5.0.dev20240514194324 on 2024-05-14 20:03

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainqueue", "0017_job_queue_jobrequest_queue_jobresult_queue"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retry_attempt", 0), ("unique_key__gt", "")),
                fields=("job_class", "unique_key"),
                name="unique_job_class_unique_key",
            ),
        ),
    ]
