# Generated by Plain 0.32.0 on 2025-03-10 15:56

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainworker", "0019_remove_jobrequest_unique_job_class_unique_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_class",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_request_uuid",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="queue",
            field=models.CharField(default="default", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="unique_key",
            field=models.CharField(max_length=255, required=False),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="job_class",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="queue",
            field=models.CharField(default="default", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="start_at",
            field=models.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="unique_key",
            field=models.CharField(max_length=255, required=False),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="ended_at",
            field=models.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="job_class",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="job_request_uuid",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="job_uuid",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="queue",
            field=models.CharField(default="default", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="started_at",
            field=models.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESSFUL", "Successful"),
                    ("ERRORED", "Errored"),
                    ("CANCELLED", "Cancelled"),
                    ("LOST", "Lost"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="unique_key",
            field=models.CharField(max_length=255, required=False),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["created_at"], name="plainworker_created_a02317_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["queue"], name="plainworker_queue_077806_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["unique_key"], name="plainworker_unique__04d87b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["started_at"], name="plainworker_started_143df5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_class"], name="plainworker_job_cla_884b46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_request_uuid"], name="plainworker_job_req_db2681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["priority"], name="plainworker_priorit_785e73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["created_at"], name="plainworker_created_c81fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(fields=["queue"], name="plainworker_queue_2614aa_idx"),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["start_at"], name="plainworker_start_a_4d6020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["unique_key"], name="plainworker_unique__21a534_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["job_class"], name="plainworker_job_cla_3e7dea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(
                fields=["created_at"], name="plainworker_created_6894c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(
                fields=["job_uuid"], name="plainworker_job_uui_8307d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(
                fields=["started_at"], name="plainworker_started_9bce76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(
                fields=["ended_at"], name="plainworker_ended_a_63caaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["status"], name="plainworker_status_a7ca35_idx"),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(
                fields=["job_request_uuid"], name="plainworker_job_req_1e1bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(
                fields=["job_class"], name="plainworker_job_cla_d138b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["queue"], name="plainworker_queue_23d8fe_idx"),
        ),
    ]
