# Generated by Plain 0.15.0 on 2025-01-07 18:45

import uuid

import plain.models.deletion
from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportFormEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("form_slug", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=plain.models.deletion.SET_NULL,
                        related_name="support_form_entries",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
