# Generated by Plain 0.15.0 on 2025-01-07 21:37

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainsupport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportformentry",
            options={"ordering": ["-created_at"]},
        ),
    ]
