# Generated by Plain 0.68.1 on 2025-09-26 18:32

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainsupport", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="supportformentry",
            name="plainsupport_supportformentry_unique_uuid",
        ),
        migrations.RemoveField(
            model_name="supportformentry",
            name="uuid",
        ),
    ]
