# Generated by Plain 0.127.2 on 2026-03-25 20:19

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainsupport",
            "0002_remove_supportformentry_plainsupport_supportformentry_unique_uuid_and_more",
        ),
    ]

    operations = []
