# Generated by Plain 0.31.0 on 2025-03-08 21:33

import uuid

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainsupport", "0002_alter_supportformentry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportformentry",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name="supportformentry",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="plainsupport_supportformentry_unique_uuid"
            ),
        ),
    ]
