# Generated by Plain 0.127.2 on 2026-03-25 22:04

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainsupport",
            "0003_rename_plainsuppor_created_bda60d_idx_plainsupport_supportformentry_created_at_idx",
        ),
    ]

    operations = [
        # Drop orphan auto-index from old db_index=True default
        migrations.RunSQL(
            'DROP INDEX IF EXISTS "plainsupport_supportformentry_user_id_b35108d7"'
        ),
    ]
