# Generated by Plain 0.47.0 on 2025-06-06 19:10

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainsupport", "0003_alter_supportformentry_uuid_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="supportformentry",
            index=models.Index(
                fields=["created_at"], name="plainsuppor_created_bda60d_idx"
            ),
        ),
    ]
