# Generated by Plain 5.0.dev20230914205221 on 2023-09-15 17:51

from bolt.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boltadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="cards",
            field=models.JSONField(default=list),
        ),
    ]
