# Generated by Plain 0.131.1 on 2026-04-03 14:47

import plain.oauth_provider.models
import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations
from plain.runtime import settings


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.settings_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthApplication",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "client_id",
                    postgres.TextField(
                        default=plain.oauth_provider.models.generate_client_id,
                        max_length=64,
                    ),
                ),
                (
                    "client_secret",
                    postgres.TextField(
                        default=plain.oauth_provider.models.generate_client_secret,
                        max_length=128,
                    ),
                ),
                ("created_at", postgres.DateTimeField(auto_now_add=True)),
                ("name", postgres.TextField(max_length=255)),
                ("redirect_uris", postgres.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "code",
                    postgres.TextField(
                        default=plain.oauth_provider.models.generate_code, max_length=64
                    ),
                ),
                ("code_challenge", postgres.TextField(max_length=128)),
                ("code_challenge_method", postgres.TextField(max_length=10)),
                ("created_at", postgres.DateTimeField(auto_now_add=True)),
                ("expires_at", postgres.DateTimeField()),
                ("redirect_uri", postgres.TextField(max_length=2000)),
                ("scope", postgres.TextField(max_length=500, required=False)),
                ("used", postgres.BooleanField(default=False)),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="plainoauthprovider.oauthapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(auto_now_add=True)),
                ("expires_at", postgres.DateTimeField()),
                ("revoked", postgres.BooleanField(default=False)),
                ("scope", postgres.TextField(max_length=500, required=False)),
                (
                    "token",
                    postgres.TextField(
                        default=plain.oauth_provider.models.generate_token,
                        max_length=64,
                    ),
                ),
                (
                    "application",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="plainoauthprovider.oauthapplication",
                    ),
                ),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("revoked", postgres.BooleanField(default=False)),
                (
                    "token",
                    postgres.TextField(
                        default=plain.oauth_provider.models.generate_token,
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="plainoauthprovider.oauthapplication",
                    ),
                ),
                (
                    "access_token",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="plainoauthprovider.accesstoken",
                    ),
                ),
            ],
        ),
    ]
