# Generated by Plain 0.49.0 on 2025-06-20 16:56

import plain.models.deletion
from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Span",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("span_id", models.CharField(max_length=255)),
                (
                    "parent_span_id",
                    models.CharField(default="", max_length=255, required=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(allow_null=True, required=False)),
                ("attributes", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Trace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("trace_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name="trace",
            constraint=models.UniqueConstraint(
                fields=("trace_id",), name="observe_unique_trace_id"
            ),
        ),
        migrations.AddField(
            model_name="span",
            name="trace",
            field=models.ForeignKey(
                on_delete=plain.models.deletion.CASCADE,
                related_name="spans",
                to="plainobserve.trace",
            ),
        ),
        migrations.AddConstraint(
            model_name="span",
            constraint=models.UniqueConstraint(
                fields=("trace", "span_id"), name="observe_unique_span_id"
            ),
        ),
    ]
