# Generated by Plain 0.49.0 on 2025-06-20 17:11

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainobserve",
            "0002_rename_parent_span_id_span_parent_id_span_context_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="span",
            name="attributes",
            field=models.JSONField(default=dict, required=False),
        ),
        migrations.AlterField(
            model_name="span",
            name="events",
            field=models.JSONField(default=list, required=False),
        ),
        migrations.AlterField(
            model_name="span",
            name="links",
            field=models.JSONField(default=list, required=False),
        ),
        migrations.AlterField(
            model_name="span",
            name="resource",
            field=models.JSONField(default=dict, required=False),
        ),
    ]
