# Generated by Plain 0.49.0 on 2025-06-20 19:49

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserve", "0003_alter_span_attributes_alter_span_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="request_id",
            field=models.CharField(default="", max_length=255, required=False),
        ),
        migrations.AddField(
            model_name="trace",
            name="session_id",
            field=models.CharField(default="", max_length=255, required=False),
        ),
        migrations.AddField(
            model_name="trace",
            name="user_id",
            field=models.CharField(default="", max_length=255, required=False),
        ),
    ]
