# Generated by Plain 0.49.0 on 2025-06-20 20:01

import plain.utils.timezone
from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserve", "0004_trace_request_id_trace_session_id_trace_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trace",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="trace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=plain.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
