# Generated by Plain 0.49.0 on 2025-06-20 20:13

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserve", "0005_alter_trace_options_trace_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="span",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AddField(
            model_name="trace",
            name="start_time",
            field=models.DateTimeField(allow_null=True, required=False),
        ),
    ]
