# Generated by Plain 0.49.0 on 2025-06-20 20:14

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserve", "0006_alter_span_options_trace_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trace",
            name="created_at",
        ),
    ]
