# Generated by Plain 0.49.0 on 2025-06-20 20:15

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserve", "0007_remove_trace_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trace",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AddField(
            model_name="trace",
            name="end_time",
            field=models.DateTimeField(allow_null=True, required=False),
        ),
    ]
