# Generated by Plain 0.52.2 on 2025-07-12 21:37

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserve", "0008_alter_trace_options_trace_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="description",
            field=models.TextField(default="", required=False),
        ),
    ]
