# Generated by Plain 0.52.2 on 2025-07-08 01:17

from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("session_key", migrations.CharField(max_length=40)),
                ("session_data", migrations.JSONField(default=dict, required=False)),
                ("created_at", migrations.DateTimeField(auto_now_add=True)),
                ("expires_at", migrations.DateTimeField(allow_null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="session",
            index=migrations.Index(
                fields=["expires_at"], name="plainsessio_expires_d87cb5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=migrations.UniqueConstraint(
                fields=("session_key",), name="unique_session_key"
            ),
        ),
    ]
