# Generated by Plain 0.150.0 on 2026-06-22 17:03

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("expires_at", postgres.DateTimeField(allow_null=True)),
                ("session_data", postgres.JSONField(default={}, required=False)),
                ("session_key", postgres.TextField(max_length=40)),
            ],
        ),
    ]
