# Generated by Plain 0.127.2 on 2026-03-25 20:19

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainsessions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="session",
            new_name="plainsessions_session_expires_at_idx",
            old_name="plainsessio_expires_d87cb5_idx",
        ),
    ]
