# Generated by Plain 0.141.1 on 2026-05-08 21:47

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "company",
                    postgres.TextField(default="", max_length=200, required=False),
                ),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("email", postgres.EmailField()),
                ("message", postgres.TextField()),
                ("name", postgres.TextField(max_length=100)),
                (
                    "subject",
                    postgres.TextField(
                        choices=[
                            ("general", "General question"),
                            ("bug", "Bug report"),
                            ("feature", "Feature request"),
                            ("billing", "Billing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subscribe", postgres.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
