from __future__ import annotations

from plain import postgres
from plain.postgres import types


@postgres.register_model
class DefaultsExample(postgres.Model):
    """Exercises Python-side literal `default=` semantics (static values,
    explicit overrides)."""

    name = types.TextField(max_length=100)
    # Static string default
    status = types.TextField(max_length=20, default="pending")
    # Static int default
    priority = types.IntegerField(default=5)
    # Nullable with a non-null default — for testing explicit-None override
    note = types.TextField(
        max_length=100, default="auto", allow_null=True, required=False
    )

    query: postgres.QuerySet[DefaultsExample] = postgres.QuerySet()


@postgres.register_model
class DBDefaultsExample(postgres.Model):
    """Model exercising DB-expression defaults (fields-db-defaults Phase 1)."""

    name = types.TextField(max_length=100)
    # Expression default — rendered as `DEFAULT gen_random_uuid()` in DDL
    db_uuid = types.UUIDField(generate=True)
    # Expression default — rendered as `DEFAULT STATEMENT_TIMESTAMP()` in DDL
    created_at = types.DateTimeField(create_now=True)
    # Expression default — per-row random string generated by Postgres
    token = types.RandomStringField(length=16)

    query: postgres.QuerySet[DBDefaultsExample] = postgres.QuerySet()

    model_options = postgres.Options(
        constraints=[
            # Constraint over an expression-default field — exercises the
            # "validate_constraints must skip DATABASE_DEFAULT" path.
            postgres.UniqueConstraint(
                fields=["db_uuid"], name="dbdefaultsexample_db_uuid_unique"
            ),
        ],
    )
