from __future__ import annotations

from datetime import datetime
from uuid import UUID

from plain import postgres
from plain.postgres import Field, types


@postgres.register_model
class DefaultsExample(postgres.Model):
    """Exercises Python-side literal `default=` semantics (static values,
    explicit overrides)."""

    name: Field[str] = types.TextField(max_length=100)
    # Static string default
    status: Field[str] = types.TextField(max_length=20, default="pending")
    # Static int default
    priority: Field[int] = types.IntegerField(default=5)
    # Nullable with a non-null default — for testing explicit-None override
    note: Field[str | None] = types.TextField(
        max_length=100, default="auto", allow_null=True, required=False
    )


@postgres.register_model
class DBDefaultsExample(postgres.Model):
    """Model exercising DB-expression defaults (fields-db-defaults Phase 1)."""

    name: Field[str] = types.TextField(max_length=100)
    # Expression default — rendered as `DEFAULT gen_random_uuid()` in DDL
    db_uuid: Field[UUID] = types.UUIDField(generate=True)
    # Expression default — rendered as `DEFAULT STATEMENT_TIMESTAMP()` in DDL
    created_at: Field[datetime] = types.DateTimeField(create_now=True)
    # Expression default — per-row random string generated by Postgres
    token: Field[str] = types.RandomStringField(length=16)

    model_options = postgres.Options(
        constraints=[
            # Constraint over an expression-default field — exercises the
            # "validate_constraints must skip DATABASE_DEFAULT" path.
            postgres.UniqueConstraint(
                fields=["db_uuid"], name="dbdefaultsexample_db_uuid_unique"
            ),
        ],
    )
