# Generated by Plain 0.52.2 on 2025-07-08 01:17

import uuid

from plain import models
from plain.models import fields, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pageview",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("uuid", fields.UUIDField(default=uuid.uuid4)),
                ("url", fields.URLField(max_length=768)),
                ("timestamp", fields.DateTimeField(auto_now_add=True)),
                ("title", fields.CharField(max_length=512, required=False)),
                ("referrer", fields.CharField(max_length=1024, required=False)),
                ("user_id", fields.CharField(max_length=255, required=False)),
                ("session_key", fields.CharField(max_length=255, required=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["timestamp"], name="plainpagevi_timesta_da4eb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user_id"], name="plainpagevi_user_id_b40ca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session_key"], name="plainpagevi_session_5545cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["url"], name="plainpagevi_url_d3e821_idx"),
        ),
        migrations.AddConstraint(
            model_name="pageview",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="plainpageviews_pageview_unique_uuid"
            ),
        ),
    ]
