# Generated by Plain 0.52.2 on 2025-07-08 01:17

import uuid

from plain import postgres
from plain.postgres import migrations
from plain.postgres.functions import Now


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pageview",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("uuid", postgres.UUIDField(default=uuid.uuid4)),
                ("url", postgres.URLField(max_length=768)),
                ("timestamp", postgres.DateTimeField(default=Now())),
                ("title", postgres.TextField(max_length=512, required=False)),
                ("referrer", postgres.TextField(max_length=1024, required=False)),
                ("user_id", postgres.TextField(max_length=255, required=False)),
                ("session_key", postgres.TextField(max_length=255, required=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
