# Generated by Plain 0.62.1 on 2025-09-10 02:26

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainpageviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pageview",
            old_name="session_key",
            new_name="session_id",
        ),
    ]
