# Generated by Plain 0.127.2 on 2026-03-25 20:19

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainpageviews", "0005_alter_pageview_url"),
    ]

    operations = []
