# Generated by Plain 0.52.2 on 2025-07-07 19:36

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainpageviews", "0006_alter_pageview_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="url",
            field=models.URLField(max_length=768),
        ),
    ]
