# Generated by Plain 0.52.2 on 2025-07-07 19:39

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plainpageviews', '0007_alter_pageview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.URLField(max_length=750),
        ),
    ]
