# Generated by Bolt 5.0.dev20240205033503 on 2024-02-05 03:42

from bolt.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0002_remove_user_is_superuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
