# Generated by Django 5.0.dev20230511190028 on 2023-05-11 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="permission",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
