# Generated by Django 5.0.dev20230815023517 on 2023-08-15 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0013_remove_user_groups_alter_permission_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
