# Generated by Plain 0.21.5 on 2025-02-17 04:24

from plain.models import fields, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("email", fields.EmailField(max_length=254)),
                ("username", fields.CharField(max_length=100)),
            ],
        ),
    ]
