# Generated by Plain 0.151.1 on 2026-07-10 21:29

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainjobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleState",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("last_enqueued_slot", postgres.DateTimeField()),
                ("schedule_key", postgres.TextField()),
            ],
            options={
                "ordering": ["schedule_key"],
            },
        ),
        # Constraints normally arrive via schema convergence, but workers
        # get_or_create ledger rows as soon as they boot — before a converge
        # step may have run — and get_or_create's race safety depends on this
        # unique constraint existing. Create it here so there is no window
        # where duplicate schedule_key rows can be inserted (which would then
        # block convergence from ever adding the constraint). Convergence
        # sees the matching name/definition and leaves it alone.
        migrations.RunSQL(
            'ALTER TABLE "plainjobs_schedulestate"'
            ' ADD CONSTRAINT "plainjobs_schedulestate_unique_schedule_key"'
            ' UNIQUE ("schedule_key")'
        ),
    ]
