# Generated by Plain 0.85.0 on 2025-11-09 03:07

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainjobs", "0006_alter_jobprocess_table_alter_jobrequest_table_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="jobrequest",
            name="plainjobs_jobrequest_unique_job_class_key",
        ),
        migrations.RemoveIndex(
            model_name="jobprocess",
            name="plainjobs_j_unique__67172c_idx",
        ),
        migrations.RemoveIndex(
            model_name="jobprocess",
            name="job_class_unique_key",
        ),
        migrations.RemoveIndex(
            model_name="jobrequest",
            name="plainjobs_j_unique__42f6a6_idx",
        ),
        migrations.RemoveIndex(
            model_name="jobrequest",
            name="job_request_class_unique_key",
        ),
        migrations.RenameField(
            model_name="jobprocess",
            old_name="unique_key",
            new_name="concurrency_key",
        ),
        migrations.RenameField(
            model_name="jobrequest",
            old_name="unique_key",
            new_name="concurrency_key",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="unique_key",
            new_name="concurrency_key",
        ),
        migrations.AlterField(
            model_name="jobprocess",
            name="priority",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobprocess",
            name="retries",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobprocess",
            name="retry_attempt",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="priority",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="retries",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="retry_attempt",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="priority",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="retries",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="retry_attempt",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESSFUL", "Successful"),
                    ("ERRORED", "Errored"),
                    ("CANCELLED", "Cancelled"),
                    ("DEFERRED", "Deferred"),
                    ("LOST", "Lost"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="jobprocess",
            index=models.Index(
                fields=["concurrency_key"], name="plainjobs_j_concurr_ad4464_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobprocess",
            index=models.Index(fields=["uuid"], name="plainjobs_j_uuid_cd8cd3_idx"),
        ),
        migrations.AddIndex(
            model_name="jobprocess",
            index=models.Index(
                fields=["job_class", "concurrency_key"], name="job_concurrency_key"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["concurrency_key"], name="plainjobs_j_concurr_c10926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(fields=["uuid"], name="plainjobs_j_uuid_c41c85_idx"),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["job_class", "concurrency_key"],
                name="job_request_concurrency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["uuid"], name="plainjobs_j_uuid_b33b4c_idx"),
        ),
    ]
