# Generated by Plain 0.124.1 on 2026-03-20 00:08

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainjobs", "0008_alter_jobrequest_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobprocess",
            name="requested_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="requested_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
    ]
