# Generated by Plain 0.139.0 on 2026-05-01 02:03

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainjobs",
            "0010_rename_plainjobs_j_created_04fbb8_idx_plainjobs_jobprocess_created_at_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobprocess",
            name="requested_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="requested_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
    ]
