# Generated by Plain 0.140.0 on 2026-05-06 04:47

import datetime
import uuid
from typing import Any

from plain import postgres
from plain.postgres import migrations

# Sentinel worker_id stamped on JobProcess rows that pre-date the heartbeat-
# based rescue mechanism. The accompanying WorkerHeartbeat row is given a
# 24-hour grace period (last_heartbeat_at = now + 24h) so any legitimately-
# still-running pre-upgrade jobs have time to finish naturally before rescue
# converts orphans to LOST. After 24h the synthetic heartbeat goes stale and
# rescue cleans up anything that didn't finish — matching the previous
# JOBS_TIMEOUT default. Tune the grace period in this migration if your
# longest legitimate pre-upgrade runtime exceeds 24h.
#
# Rolling-deploy safety: after the backfill runs, this migration alters
# worker_id to NOT NULL. Any old worker still trying to convert a JobRequest
# without supplying a worker_id will hit the constraint and fail loudly,
# leaving the JobRequest in queue for a new worker to pick up — strictly
# better than silently inserting unrescuable NULL rows.
_PRE_HEARTBEAT_WORKER_ID = uuid.UUID("00000000-0000-0000-0000-000000000000")
_UPGRADE_GRACE = datetime.timedelta(hours=24)


def _backfill_unstamped_job_processes(apps: Any, schema_editor: Any) -> None:
    JobProcess = apps.get_model("plainjobs", "JobProcess")
    WorkerHeartbeat = apps.get_model("plainjobs", "WorkerHeartbeat")

    if not JobProcess.query.filter(worker_id__isnull=True).exists():
        return

    now = datetime.datetime.now(datetime.UTC)
    WorkerHeartbeat.query.create(
        worker_id=_PRE_HEARTBEAT_WORKER_ID,
        hostname="<pre-heartbeat-upgrade>",
        pid=0,
        queues=[],
        started_at=now,
        last_heartbeat_at=now + _UPGRADE_GRACE,
    )
    JobProcess.query.filter(worker_id__isnull=True).update(
        worker_id=_PRE_HEARTBEAT_WORKER_ID
    )


class Migration(migrations.Migration):
    dependencies = [
        ("plainjobs", "0011_jobprocess_requested_at_jobresult_requested_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("hostname", postgres.TextField(max_length=255)),
                ("last_heartbeat_at", postgres.DateTimeField()),
                ("pid", postgres.IntegerField()),
                ("queues", postgres.JSONField()),
                ("started_at", postgres.DateTimeField(create_now=True)),
                ("worker_id", postgres.UUIDField()),
            ],
            options={
                "ordering": ["-last_heartbeat_at"],
            },
        ),
        migrations.AddField(
            model_name="jobprocess",
            name="worker_id",
            field=postgres.UUIDField(allow_null=True, required=False),
        ),
        migrations.RunPython(_backfill_unstamped_job_processes),
        migrations.AlterField(
            model_name="jobprocess",
            name="worker_id",
            field=postgres.UUIDField(),
        ),
    ]
