# Generated by Plain 0.52.2 on 2025-07-08 01:17

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("from_pattern", postgres.TextField(max_length=255)),
                ("to_pattern", postgres.TextField(max_length=255)),
                ("http_status", postgres.SmallIntegerField(default=301)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("updated_at", postgres.DateTimeField(update_now=True)),
                ("order", postgres.SmallIntegerField(default=0)),
                ("enabled", postgres.BooleanField(default=True)),
                ("is_regex", postgres.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RedirectLog",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("from_url", postgres.URLField(max_length=512)),
                ("to_url", postgres.URLField(max_length=512)),
                ("http_status", postgres.SmallIntegerField(default=301)),
                ("ip_address", postgres.GenericIPAddressField()),
                ("user_agent", postgres.TextField(max_length=512, required=False)),
                ("referrer", postgres.TextField(max_length=512, required=False)),
                ("created_at", postgres.DateTimeField(create_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotFoundLog",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("url", postgres.URLField(max_length=512)),
                ("ip_address", postgres.GenericIPAddressField()),
                ("user_agent", postgres.TextField(max_length=512, required=False)),
                ("referrer", postgres.TextField(max_length=512, required=False)),
                ("created_at", postgres.DateTimeField(create_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="redirectlog",
            name="redirect",
            field=postgres.ForeignKeyField(
                on_delete=plain.postgres.deletion.CASCADE,
                to="plainredirection.redirect",
            ),
        ),
    ]
