# Generated by Plain 0.150.0 on 2026-06-22 17:03

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotFoundLog",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("ip_address", postgres.GenericIPAddressField()),
                ("referrer", postgres.TextField(max_length=512, required=False)),
                ("url", postgres.URLField(max_length=512)),
                ("user_agent", postgres.TextField(max_length=512, required=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("enabled", postgres.BooleanField(default=True)),
                ("from_pattern", postgres.TextField(max_length=255)),
                ("http_status", postgres.SmallIntegerField(default=301)),
                ("is_regex", postgres.BooleanField(default=False)),
                ("order", postgres.SmallIntegerField(default=0)),
                ("to_pattern", postgres.TextField(max_length=255)),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RedirectLog",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("from_url", postgres.URLField(max_length=512)),
                ("http_status", postgres.SmallIntegerField(default=301)),
                ("ip_address", postgres.GenericIPAddressField()),
                ("referrer", postgres.TextField(max_length=512, required=False)),
                ("to_url", postgres.URLField(max_length=512)),
                ("user_agent", postgres.TextField(max_length=512, required=False)),
                (
                    "redirect",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="plainredirection.redirect"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
