# Generated by Plain 0.52.2 on 2025-07-08 01:17

from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("from_pattern", migrations.CharField(max_length=255)),
                ("to_pattern", migrations.CharField(max_length=255)),
                ("http_status", migrations.PositiveSmallIntegerField(default=301)),
                ("created_at", migrations.DateTimeField(auto_now_add=True)),
                ("updated_at", migrations.DateTimeField(auto_now=True)),
                ("order", migrations.PositiveSmallIntegerField(default=0)),
                ("enabled", migrations.BooleanField(default=True)),
                ("is_regex", migrations.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RedirectLog",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("from_url", migrations.URLField(max_length=512)),
                ("to_url", migrations.URLField(max_length=512)),
                ("http_status", migrations.PositiveSmallIntegerField(default=301)),
                ("ip_address", migrations.GenericIPAddressField()),
                ("user_agent", migrations.CharField(max_length=512, required=False)),
                ("referrer", migrations.CharField(max_length=512, required=False)),
                ("created_at", migrations.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotFoundLog",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("url", migrations.URLField(max_length=512)),
                ("ip_address", migrations.GenericIPAddressField()),
                ("user_agent", migrations.CharField(max_length=512, required=False)),
                ("referrer", migrations.CharField(max_length=512, required=False)),
                ("created_at", migrations.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="redirect",
            index=migrations.Index(
                fields=["order"], name="plainredire_order_44dde0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redirect",
            index=migrations.Index(
                fields=["created_at"], name="plainredire_created_18c288_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=migrations.UniqueConstraint(
                fields=("from_pattern",),
                name="plainredirects_redirect_unique_from_pattern",
            ),
        ),
        migrations.AddField(
            model_name="redirectlog",
            name="redirect",
            field=migrations.ForeignKey(
                on_delete=migrations.CASCADE, to="plainredirection.redirect"
            ),
        ),
        migrations.AddIndex(
            model_name="notfoundlog",
            index=migrations.Index(
                fields=["created_at"], name="plainredire_created_d5f0c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redirectlog",
            index=migrations.Index(
                fields=["created_at"], name="plainredire_created_5d75f4_idx"
            ),
        ),
    ]
