# Generated by Plain 0.151.1 on 2026-06-30 15:55

from plain import postgres
from plain.postgres import migrations


def aggregate_duplicate_urls(models, schema_editor):
    """Collapse the pre-aggregation 404 log (one row per hit) into one row per URL.

    The old schema inserted a row for every 404, so the same URL appears many
    times. The new unique constraint on `url` (added by convergence right after
    this migration) can't be created while those duplicates exist, so fold each
    URL's rows into a single survivor that carries the hit count and the most
    recent hit's metadata.
    """
    NotFoundLog = models.get_model("plainredirection", "notfoundlog")

    # url -> the aggregate values for the row we keep. Iteration is
    # first_seen-ordered, so the last hit folded into each URL is its most recent.
    survivors = {}
    for log in NotFoundLog.query.all().order_by("first_seen", "id"):
        survivor = survivors.get(log.url)
        if survivor is None:
            # First sighting of this URL becomes the row we keep. Its own
            # first_seen is both the first and (so far) last time we saw it.
            survivors[log.url] = {
                "id": log.id,
                "count": 1,
                "last_seen": log.first_seen,
                "ip_address": log.ip_address,
                "user_agent": log.user_agent,
                "referrer": log.referrer,
            }
            continue

        # A repeat 404 for a URL we've already kept: bump the count, advance
        # last_seen, and carry this (more recent) hit's metadata forward.
        survivor["count"] += 1
        survivor["last_seen"] = log.first_seen
        survivor["ip_address"] = log.ip_address
        survivor["user_agent"] = log.user_agent
        survivor["referrer"] = log.referrer
        log.delete()

    # One set-based update per survivor writes the computed columns by id
    # without rehydrating each instance.
    for survivor in survivors.values():
        NotFoundLog.query.filter(id=survivor.pop("id")).update(**survivor)


class Migration(migrations.Migration):
    dependencies = [
        ("plainredirection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notfoundlog",
            options={"ordering": ["-last_seen"]},
        ),
        migrations.RenameField(
            model_name="notfoundlog",
            old_name="created_at",
            new_name="first_seen",
        ),
        migrations.AddField(
            model_name="notfoundlog",
            name="count",
            field=postgres.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="notfoundlog",
            name="last_seen",
            field=postgres.DateTimeField(create_now=True),
        ),
        migrations.AlterField(
            model_name="notfoundlog",
            name="url",
            field=postgres.TextField(max_length=512),
        ),
        migrations.RunPython(aggregate_duplicate_urls),
    ]
