# Generated by Plain 0.20.0 on 2025-02-05 20:12

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainredirection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="redirect",
            name="is_regex",
            field=models.BooleanField(default=False),
        ),
    ]
