# Generated by Plain 0.21.0 on 2025-02-05 21:58

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainredirection", "0002_redirect_enabled_redirect_is_regex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="from_pattern",
            field=models.CharField(max_length=255),
        ),
    ]
