# Generated by Plain 0.127.2 on 2026-03-25 22:04

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainredirection",
            "0002_rename_plainredire_created_d5f0c7_idx_plainredirection_notfoundlog_created_at_idx_and_more",
        ),
    ]

    operations = [
        # Drop orphan auto-index from old db_index=True default
        migrations.RunSQL(
            'DROP INDEX IF EXISTS "plainredirection_redirectlog_redirect_id_72c2ae26"'
        ),
        migrations.AddIndex(
            model_name="redirectlog",
            index=postgres.Index(
                fields=["redirect"], name="plainredirection_redirectlog_redirect_id_idx"
            ),
        ),
    ]
