# Generated by Plain 0.21.1 on 2025-02-06 16:38

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainredirection",
            "0004_alter_notfoundlog_referer_alter_redirectlog_referer",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notfoundlog",
            name="referer",
            field=models.CharField(required=False, max_length=512),
        ),
        migrations.AlterField(
            model_name="notfoundlog",
            name="user_agent",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="redirectlog",
            name="referer",
            field=models.CharField(required=False, max_length=512),
        ),
        migrations.AlterField(
            model_name="redirectlog",
            name="user_agent",
            field=models.CharField(max_length=512),
        ),
    ]
