# Generated by Plain 0.21.1 on 2025-02-06 17:59

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainredirection", "0006_alter_notfoundlog_user_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="http_status",
            field=models.PositiveSmallIntegerField(default=301),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="redirectlog",
            name="http_status",
            field=models.PositiveSmallIntegerField(default=301),
        ),
    ]
