# Generated by Plain 0.21.1 on 2025-02-07 19:59

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainredirection",
            "0007_alter_redirect_http_status_alter_redirect_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notfoundlog",
            name="url",
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name="redirectlog",
            name="from_url",
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name="redirectlog",
            name="to_url",
            field=models.URLField(max_length=512),
        ),
    ]
