# Generated by Plain 0.31.0 on 2025-03-10 15:43

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainredirection", "0010_alter_redirect_from_pattern_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="redirect",
            index=models.Index(fields=["order"], name="plainredire_order_44dde0_idx"),
        ),
    ]
