# Generated by Plain 0.47.0 on 2025-06-06 19:11

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainredirection", "0011_alter_redirect_order_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notfoundlog",
            index=models.Index(
                fields=["created_at"], name="plainredire_created_d5f0c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redirect",
            index=models.Index(
                fields=["created_at"], name="plainredire_created_18c288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redirectlog",
            index=models.Index(
                fields=["created_at"], name="plainredire_created_5d75f4_idx"
            ),
        ),
    ]
