# Generated by Plain 0.150.0 on 2026-06-22 17:03

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("api_version", postgres.TextField(max_length=255, required=False)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("expires_at", postgres.DateTimeField(allow_null=True, required=False)),
                (
                    "last_used_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                ("name", postgres.TextField(max_length=255, required=False)),
                ("token", postgres.RandomStringField(length=40)),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
                ("uuid", postgres.UUIDField(generate=True)),
            ],
        ),
    ]
