# Generated by Plain 0.52.2 on 2025-07-08 01:17

import uuid

import plain.api.models
from plain import postgres
from plain.postgres import migrations
from plain.postgres.functions import Now


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("uuid", postgres.UUIDField(default=uuid.uuid4)),
                ("created_at", postgres.DateTimeField(default=Now())),
                ("updated_at", postgres.DateTimeField(auto_now=True)),
                ("expires_at", postgres.DateTimeField(allow_null=True, required=False)),
                (
                    "last_used_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                ("name", postgres.TextField(max_length=255, required=False)),
                (
                    "token",
                    postgres.TextField(
                        default=plain.api.models.generate_token, max_length=40
                    ),
                ),
                ("api_version", postgres.TextField(max_length=255, required=False)),
            ],
        ),
    ]
