# Generated by Plain 0.17.0 on 2025-01-22 21:02

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(required=False, allow_null=True),
        ),
    ]
