# Generated by Plain 0.31.0 on 2025-03-08 21:33

import uuid

import plain.api.models
from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainapi", "0002_apikey_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="token",
            field=models.CharField(
                default=plain.api.models.generate_token, max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="plainapi_apikey_unique_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.UniqueConstraint(
                fields=("token",), name="plainapi_apikey_unique_token"
            ),
        ),
    ]
