# Generated by Plain 0.37.0 on 2025-04-09 17:21

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainapi", "0004_apikey_version_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apikey",
            old_name="version_name",
            new_name="api_version_name",
        ),
    ]
