# Generated by Plain 0.38.0 on 2025-04-13 15:26

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainapi", "0005_rename_version_name_apikey_api_version_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apikey",
            old_name="api_version_name",
            new_name="api_version",
        ),
    ]
