# Generated by Plain 0.141.1 on 2026-05-08 21:47

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_user_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("name", postgres.TextField(max_length=100)),
                (
                    "owner",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        related_query_name="projects",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("due_date", postgres.DateField(allow_null=True, required=False)),
                ("is_complete", postgres.BooleanField(default=False)),
                ("notes", postgres.TextField(default="", required=False)),
                (
                    "priority",
                    postgres.TextField(
                        choices=[
                            ("low", "Low"),
                            ("med", "Medium"),
                            ("high", "High"),
                            ("urg", "Urgent"),
                        ],
                        default="med",
                        max_length=4,
                    ),
                ),
                ("title", postgres.TextField(max_length=200)),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
                (
                    "owner",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        related_query_name="tasks",
                        to="users.user",
                    ),
                ),
                (
                    "project",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.SET_NULL,
                        related_query_name="tasks",
                        required=False,
                        to="tasks.project",
                    ),
                ),
            ],
            options={
                "ordering": ["is_complete", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=40)),
                (
                    "owner",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        related_query_name="tags",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaskTag",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "task",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="tasks.task"
                    ),
                ),
                (
                    "tag",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="tasks.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=postgres.ManyToManyField(through="tasks.TaskTag", to="tasks.tag"),
        ),
    ]
