# Generated by Plain 5.0.dev20230914205221 on 2023-09-15 17:51

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="cards",
            field=models.JSONField(default=list),
        ),
    ]
