# Generated by Plain 5.0.dev20230915175420 on 2023-09-18 19:08

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainadmin", "0002_alter_dashboard_cards"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
