# Generated by Plain 0.150.0 on 2026-06-22 17:03

import plain.postgres.fields.encrypted
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthConnection",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "access_token",
                    plain.postgres.fields.encrypted.EncryptedTextField(max_length=2000),
                ),
                (
                    "access_token_expires_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("provider_key", postgres.TextField(max_length=100)),
                ("provider_user_id", postgres.TextField(max_length=100)),
                (
                    "refresh_token",
                    plain.postgres.fields.encrypted.EncryptedTextField(
                        max_length=2000, required=False
                    ),
                ),
                (
                    "refresh_token_expires_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "ordering": ("provider_key",),
            },
        ),
    ]
