# Generated by Plain 0.52.2 on 2025-07-08 01:17

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthConnection",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
                ("provider_key", postgres.TextField(max_length=100)),
                ("provider_user_id", postgres.TextField(max_length=100)),
                ("access_token", postgres.TextField(max_length=2000)),
                ("refresh_token", postgres.TextField(max_length=2000, required=False)),
                (
                    "access_token_expires_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                (
                    "refresh_token_expires_at",
                    postgres.DateTimeField(allow_null=True, required=False),
                ),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="users.User",
                    ),
                ),
            ],
            options={
                "ordering": ("provider_key",),
            },
        ),
    ]
