# Generated by Plain 0.124.0 on 2026-03-16 14:33

import plain.postgres.fields.encrypted
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainoauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthconnection",
            name="access_token",
            field=plain.postgres.fields.encrypted.EncryptedTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="oauthconnection",
            name="refresh_token",
            field=plain.postgres.fields.encrypted.EncryptedTextField(
                max_length=2000, required=False
            ),
        ),
    ]
