# Generated by Plain 0.127.2 on 2026-03-25 22:04

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainoauth", "0002_alter_oauthconnection_access_token_and_more"),
    ]

    operations = [
        # Drop orphan auto-index from old db_index=True default
        migrations.RunSQL(
            'DROP INDEX IF EXISTS "plainoauth_oauthconnection_user_id_f1392e9b"'
        ),
    ]
