# Generated by Plain 0.13.1 on 2025-02-16 23:02

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("make", postgres.TextField(max_length=100)),
                ("model", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=postgres.UniqueConstraint(
                fields=("make", "model"), name="unique_make_model"
            ),
        ),
    ]
