# Generated by Plain 0.52.2 on 2025-07-02 18:16

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0002_test_field_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteParent",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChildSetNull",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=plain.postgres.deletion.SET_NULL,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildSetDefault",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        default=1,
                        on_delete=plain.postgres.deletion.SET_DEFAULT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildDoNothing",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.DO_NOTHING,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildCascade",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildRestrict",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.RESTRICT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildProtect",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.PROTECT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
    ]
