# Generated by Plain 0.72.2 on 2025-10-07 18:23

import app.examples.models.mixins

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0003_deleteparent_childsetnull_childsetdefault_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultQuerySetModel",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MixinTestModel",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("updated_at", postgres.DateTimeField(update_now=True)),
                ("name", postgres.TextField(max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(app.examples.models.mixins.TimestampMixin, postgres.Model),
        ),
        migrations.CreateModel(
            name="CustomQuerySetModel",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CustomSpecialQuerySetModel",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="childcascade",
            name="parent",
            field=postgres.ForeignKeyField(
                on_delete=plain.postgres.deletion.CASCADE,
                to="examples.deleteparent",
            ),
        ),
    ]
