# Generated by Plain 0.88.0 on 2025-11-14 19:44

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0004_defaultquerysetmodel_mixintestmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CarFeature",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "car",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE, to="examples.car"
                    ),
                ),
                (
                    "feature",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE, to="examples.feature"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="features",
            field=postgres.ManyToManyField(
                through="examples.CarFeature",
                to="examples.feature",
            ),
        ),
    ]
