# Generated by Plain 0.130.1 on 2026-03-29 22:18

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0006_secretstore"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeNode",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="examples.treenode",
                    ),
                ),
            ],
            options={
                "indexes": [],
                "constraints": [],
            },
        ),
        migrations.CreateModel(
            name="UnconstrainedChild",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        db_constraint=False,
                        on_delete=plain.postgres.deletion.NO_ACTION,
                        to="examples.deleteparent",
                    ),
                ),
            ],
            options={
                "indexes": [],
                "constraints": [],
            },
        ),
    ]
