# Generated by Plain 0.132.0 on 2026-04-13 20:13

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0007_treenode_unconstrainedchild"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiamondParentA",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MidParent",
            fields=[
                ("id", postgres.PrimaryKeyField()),
            ],
        ),
        migrations.CreateModel(
            name="DiamondParentB",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Grandparent",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DiamondChild",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent_a",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="examples.diamondparenta",
                    ),
                ),
                (
                    "parent_b",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="examples.diamondparentb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grandchild",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "mid_parent",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="examples.midparent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="midparent",
            name="grandparent",
            field=postgres.ForeignKeyField(
                on_delete=plain.postgres.deletion.CASCADE, to="examples.grandparent"
            ),
        ),
    ]
