# Generated by Plain 0.132.0 on 2026-04-13 20:22

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0008_setsentinelparent_diamondparenta_midparent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CircB",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CircA",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
                (
                    "partner",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=plain.postgres.deletion.CASCADE,
                        required=False,
                        to="examples.circb",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="circb",
            name="partner",
            field=postgres.ForeignKeyField(
                allow_null=True,
                on_delete=plain.postgres.deletion.CASCADE,
                required=False,
                to="examples.circa",
            ),
        ),
    ]
