# Generated by Plain 0.132.0 on 2026-04-14 14:08

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0009_circb_circa_circb_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="HideableItem",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
    ]
