# Generated by Plain 0.132.1 on 2026-04-14 18:34

import uuid

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0010_hideableitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultsExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
                (
                    "note",
                    postgres.TextField(
                        allow_null=True, default="auto", max_length=100, required=False
                    ),
                ),
                ("priority", postgres.IntegerField(default=5)),
                ("status", postgres.TextField(default="pending", max_length=20)),
                ("token_uuid", postgres.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
