# Generated by Plain 0.132.1 on 2026-04-14 18:52

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0011_defaultsexample"),)

    operations = (
        migrations.CreateModel(
            name="IterationExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
                ("tag", postgres.TextField(max_length=100)),
            ],
        ),
    )
