# Generated by Plain 0.132.1 on 2026-04-14 18:54

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0012_iterationexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("description", postgres.TextField(max_length=100)),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ConstraintExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("description", postgres.TextField(max_length=100)),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NullabilityExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("required_text", postgres.TextField(max_length=100)),
            ],
        ),
    ]
