# Generated by Plain 0.132.1 on 2026-04-14 19:12

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0013_indexexample_constraintexample_nullabilityexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
                ("size", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Feature",
            new_name="Tag",
        ),
        migrations.RemoveField(
            model_name="carfeature",
            name="car",
        ),
        migrations.RemoveField(
            model_name="carfeature",
            name="feature",
        ),
        migrations.CreateModel(
            name="WidgetTag",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "tag",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.tag"
                    ),
                ),
                (
                    "widget",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.widget"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="widget",
            name="tags",
            field=postgres.ManyToManyField(
                through="examples.WidgetTag", to="examples.tag"
            ),
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="CarFeature",
        ),
    ]
