# Generated by Plain 0.132.1 on 2026-04-14 19:29

import plain.postgres.functions.datetime
import plain.postgres.functions.uuid
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0014_widget_rename_feature_tag_remove_carfeature_car_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBDefaultsExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "created_at",
                    postgres.DateTimeField(
                        default=plain.postgres.functions.datetime.Now()
                    ),
                ),
                (
                    "db_uuid",
                    postgres.UUIDField(
                        default=plain.postgres.functions.uuid.GenRandomUUID()
                    ),
                ),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
    ]
