# Generated by Plain 0.132.1 on 2026-04-14 19:29

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0014_widget_rename_feature_tag_remove_carfeature_car_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBDefaultsExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("db_uuid", postgres.UUIDField(generate=True)),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
    ]
