# Generated by Plain 0.132.1 on 2026-04-15 12:00

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0015_dbdefaultsexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormsExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("amount", postgres.DecimalField(decimal_places=2, max_digits=10)),
                ("count", postgres.IntegerField()),
                ("duration", postgres.DurationField()),
                ("event_date", postgres.DateField()),
                ("event_datetime", postgres.DateTimeField()),
                ("event_time", postgres.TimeField()),
                ("external_id", postgres.UUIDField()),
                ("is_active", postgres.BooleanField(default=True)),
                ("name", postgres.TextField(max_length=100)),
                (
                    "note",
                    postgres.TextField(allow_null=True, max_length=200, required=False),
                ),
                ("ratio", postgres.FloatField()),
                (
                    "status",
                    postgres.TextField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
