# Generated by Plain 0.132.1 on 2026-04-16 05:45

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0016_formsexample"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbdefaultsexample",
            name="token",
            field=postgres.RandomStringField(length=16),
        ),
    ]
