# Generated by Plain 0.154.0 on 2026-07-23 15:32

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0018_storageparametersexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShadowTarget",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("field", postgres.TextField(max_length=100)),
                ("get_prefetch_queryset", postgres.TextField(max_length=100)),
                ("get_queryset", postgres.TextField(max_length=100)),
                ("is_cached", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ShadowSource",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "ref",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.shadowtarget"
                    ),
                ),
            ],
        ),
    ]
