# Generated by Plain 0.154.0 on 2026-07-23 16:03

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0018_storageparametersexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturningEvent",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("count", postgres.IntegerField(default=0)),
                ("label", postgres.TextField(max_length=100)),
                ("payload", postgres.JSONField(allow_null=True, required=False)),
            ],
        ),
    ]
