# Generated by Plain 0.163.1 on 2026-09-19 02:12

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0018_storageparametersexample"),)

    operations = (
        migrations.CreateModel(
            name="ValueTypeExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("location", postgres.JSONField(allow_null=True, default=None)),
                ("name", postgres.TextField(max_length=50)),
                ("slug", postgres.TextField()),
            ],
        ),
    )
