# Generated by Plain 0.154.0 on 2026-07-23 15:32

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0018_storageparametersexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturningEvent",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("count", postgres.IntegerField(default=0)),
                ("label", postgres.TextField(max_length=100)),
                ("payload", postgres.JSONField(allow_null=True, required=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReturningParent",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ReturningChild",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                (
                    "parent",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.returningparent"
                    ),
                ),
            ],
        ),
    ]
