# Generated by Plain 0.163.1 on 2026-09-19 02:31

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0019_shadowtarget_shadowsource"),)

    operations = (
        migrations.CreateModel(
            name="StringConditionsExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("ip", postgres.GenericIPAddressField()),
                ("label", postgres.TextField(max_length=50)),
                ("token", postgres.RandomStringField(length=16)),
            ],
        ),
    )
