# Generated by Plain 0.154.0 on 2026-07-23 16:24

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0019_returningevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpsertItem",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("key", postgres.TextField(max_length=100)),
                ("label", postgres.TextField(default="")),
                ("value", postgres.IntegerField(default=0)),
            ],
        ),
    ]
