# Generated by Plain 0.154.0 on 2026-07-23 17:30

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0020_upsertitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpsertOwner",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="upsertitem",
            name="owner",
            field=postgres.ForeignKeyField(
                allow_null=True, on_delete=postgres.CASCADE, to="examples.upsertowner"
            ),
        ),
    ]
