# Generated by Plain 0.163.1 on 2026-09-20 02:36

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0021_returningevent"),)

    operations = (
        migrations.CreateModel(
            name="AliasCollisionExample",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("f1", postgres.TextField(default="", max_length=100, required=False)),
                ("name", postgres.TextField(max_length=100)),
                (
                    "upper1",
                    postgres.TextField(default="", max_length=100, required=False),
                ),
            ],
        ),
    )
