# Generated by Plain 0.163.1 on 2026-09-19 18:54

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0022_upsertitem"),)

    operations = (
        migrations.CreateModel(
            name="UpsertPair",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("bucket", postgres.TextField(max_length=100)),
                ("slug", postgres.TextField(max_length=100)),
                ("value", postgres.IntegerField(default=0)),
            ],
        ),
    )
