# Generated by Plain 0.163.1 on 2026-09-19 19:56

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0023_upsertowner_upsertitem_owner"),)

    operations = (
        migrations.CreateModel(
            name="UpsertScope",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UpsertScopedItem",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("key", postgres.TextField(max_length=100)),
                ("value", postgres.IntegerField(default=0)),
                (
                    "scope",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.upsertscope"
                    ),
                ),
            ],
        ),
    )
