# Generated by Plain 0.163.1 on 2026-09-19 19:26

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0023_upsertpair"),)

    operations = (
        migrations.CreateModel(
            name="UpsertTenant",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UpsertValueKey",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("blob", postgres.BinaryField()),
                ("payload", postgres.JSONField()),
                ("value", postgres.IntegerField(default=0)),
                ("zone", postgres.TimeZoneField()),
            ],
        ),
        migrations.CreateModel(
            name="UpsertScoped",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("slug", postgres.TextField(max_length=100)),
                ("value", postgres.IntegerField(default=0)),
                (
                    "tenant",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.upserttenant"
                    ),
                ),
            ],
        ),
    )
