# Generated by Plain 0.163.1 on 2026-09-19 19:44

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0024_upserttenant_upsertvaluekey_upsertscoped"),)

    operations = (
        migrations.CreateModel(
            name="UpsertFloatKey",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("score", postgres.FloatField()),
                ("value", postgres.IntegerField(default=0)),
            ],
        ),
    )
