# Generated by Plain 0.163.1 on 2026-09-20 02:00

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0025_upsertfloatkey"),)

    operations = (
        migrations.CreateModel(
            name="UpsertDecimalKey",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("amount", postgres.DecimalField(decimal_places=4, max_digits=12)),
                ("value", postgres.IntegerField(default=0)),
            ],
        ),
    )
