# Generated by Plain 0.166.0 on 2026-10-08 17:03

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("examples", "0028_aliascollisionexample"),)

    operations = (
        migrations.CreateModel(
            name="DescribedPerson",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("name", postgres.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DescribedProfile",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("bio", postgres.TextField(default="", required=False)),
                (
                    "person",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.describedperson"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DescribedSlot",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("active", postgres.BooleanField(default=False)),
                ("position", postgres.IntegerField(default=0)),
                (
                    "owner",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="examples.describedperson"
                    ),
                ),
            ],
        ),
    )
