"""Synthesize a Python module from a `.html` template for type checking.

Walks the tokenizer's flat output (so we get accurate offsets for free)
and emits a Python module that mirrors the template's expression scope:

- `imports:` block becomes real top-of-module imports
- `attrs:` declarations become typed keyword-only parameters
- `slots:` declarations become `SafeString` parameters
- Each `{expr}` (text or attribute position) becomes a typed statement
- `:if={cond}` becomes a flat expression check (walrus still binds)
- `:for={target in iter}` opens a real `for`-block so subsequent
  expressions inside the loop see the loop variable in scope
- `:include="..."` is structural; `:include={expr}` checks the path expr

A line-keyed source map records `synth_line → (template_offset, kind)`
so backend diagnostics can be re-anchored to the template later.
"""

from __future__ import annotations

import ast
import keyword
from dataclasses import dataclass, field

from ..parser import _parse_for_clause
from ..tokenizer import (
    AttrExpr,
    Attribute,
    EndTagToken,
    ExprToken,
    StartTagToken,
    Token,
    tokenize,
)
from ._ast_utils import dotted_chain
from .declarations import (
    AttrDeclaration,
    Declarations,
    ImportDeclaration,
)


@dataclass
class SourceMapEntry:
    """One synthesized line's link back to the template."""

    template_offset: int
    kind: str  # "expr" | "if" | "for-iter" | "include-path" | "attr-expr"


@dataclass
class Synthesis:
    """A synthesized module + the mapping back to template positions."""

    source: str
    line_map: dict[int, SourceMapEntry] = field(default_factory=dict)


# Bumped whenever the synthesized layout changes — invalidates cached
# results without the user touching anything else.
FORMAT_VERSION = 2


def synthesize(body: str, declarations: Declarations) -> Synthesis:
    """Build the synthesized module from a template body and declarations."""
    tokens = tokenize(body)
    builder = _Builder(declarations)
    builder.emit_prelude()
    builder.walk(tokens)
    builder.emit_postlude()
    return builder.finish()


_BUILTIN_TYPE_NAMES = {
    "Any",
    "Literal",
    "Optional",
    "Union",
    "TypedDict",
    "Callable",
    "Sequence",
    "Iterable",
    "Mapping",
    "MutableMapping",
}


class _Builder:
    def __init__(self, declarations: Declarations) -> None:
        self._decls = declarations
        self._lines: list[str] = []
        self._line_map: dict[int, SourceMapEntry] = {}
        self._indent = 0
        # Stack of indents that were opened by a `:for` on a non-self-closing
        # element. Each entry is the indent level we should pop back to when
        # the matching end tag closes.
        self._scope_stack: list[_Scope] = []

    def emit_prelude(self) -> None:
        self._lines.append("# Auto-generated by plain.html for type checking.")
        self._lines.append("# Do not edit.")
        self._lines.append("from __future__ import annotations")
        self._lines.append("")
        self._lines.append("from typing import Any, Literal, Optional, Union")
        self._lines.append("from collections.abc import (")
        self._lines.append("    Callable,")
        self._lines.append("    Iterable,")
        self._lines.append("    Mapping,")
        self._lines.append("    MutableMapping,")
        self._lines.append("    Sequence,")
        self._lines.append(")")
        self._lines.append("from plain.utils.safestring import SafeString")
        self._lines.append("")

        for imp_stmt in self._inferred_module_imports():
            self._lines.append(imp_stmt)

        for imp in self._decls.imports:
            self._emit_import(imp)

        self._lines.append("")
        self._lines.append("def _plain_html_check(")
        self._emit_attr_params()
        self._emit_slot_params()
        self._lines.append(") -> None:")
        # Function body always starts indented one step.
        self._indent = 1
        # Body must have at least one statement.
        self._lines.append(self._ind() + "_unused = None")

    def emit_postlude(self) -> None:
        # `_plain_html_check` is intentionally unused — silence "unused"
        # diagnostics by referencing it once at module scope.
        self._lines.append("")
        self._lines.append("_ = _plain_html_check")

    def finish(self) -> Synthesis:
        return Synthesis(
            source="\n".join(self._lines) + "\n",
            line_map=self._line_map,
        )

    # --- token walk -----------------------------------------------------

    def walk(self, tokens: list[Token]) -> None:
        for tok in tokens:
            match tok:
                case ExprToken():
                    self._emit_expr(tok.code, tok.offset, kind="expr")
                case StartTagToken():
                    self._handle_start_tag(tok)
                case EndTagToken():
                    self._handle_end_tag()
                # Text, doctype, HTML comments, template comments contribute
                # no expressions worth type-checking.
                case _:
                    pass

    def _handle_start_tag(self, tok: StartTagToken) -> None:
        # Order matters: a `:for` on the same tag binds the loop variable
        # *before* the other attributes are evaluated, since attributes
        # like `href={tab["view"]...}` reference the loop var. So we open
        # the for-block first, then emit attribute checks inside it.
        for_clause: str | None = None
        if_code: str | None = None
        include_path_expr: str | None = None
        regular_attrs: list[Attribute] = []

        for attr in tok.attrs:
            match attr.name:
                case ":if":
                    if_code = _single_expr_value(attr)
                case ":for":
                    raw = _single_expr_value(attr)
                    if raw is not None:
                        for_clause = raw
                case ":include":
                    include_path_expr = _single_expr_value(attr)
                case _:
                    regular_attrs.append(attr)

        opened_for = False
        opened_if = False
        if for_clause is not None:
            try:
                clause = _parse_for_clause(for_clause)
            except Exception:
                # Phase 8 surfaces this as a structural error; skip here.
                return
            self._emit_typed_expr(
                clause.iter_code,
                tok.offset,
                kind="for-iter",
                typ="Iterable[Any]",
            )
            target = clause.raw_target or ", ".join(clause.targets)
            self._lines.append(self._ind() + f"for {target} in ({clause.iter_code}):")
            self._indent += 1
            self._lines.append(self._ind() + "_unused = None")
            opened_for = True

        if if_code is not None:
            # Emit a real `if (cond):` block (rather than a flat
            # `_ = (cond)`) so ty narrows `cond`'s type within the
            # element's body — `<template :if={task.project}>` makes
            # `task.project.name` inside the body checkable without a
            # second guard.
            wrapped = self._safe_expr(if_code)
            self._record_line(tok.offset, "if")
            self._lines.append(self._ind() + f"if ({wrapped}):")
            self._indent += 1
            self._lines.append(self._ind() + "_unused = None")
            opened_if = True

        if include_path_expr is not None:
            # Dynamic `:include={path_expr}` must be str-compatible.
            self._emit_typed_expr(
                include_path_expr, tok.offset, kind="include-path", typ="str"
            )

        for attr in regular_attrs:
            self._emit_attr_expressions(attr, tok.offset)

        scope = _Scope(opened_for=opened_for, opened_if=opened_if, tag=tok.name)

        # Self-closing or void tags don't open a child scope.
        from ..tokenizer import VOID_ELEMENTS

        if tok.self_closing or tok.name in VOID_ELEMENTS:
            if scope.opened_if:
                self._indent -= 1
            if scope.opened_for:
                self._indent -= 1
            return

        self._scope_stack.append(scope)

    def _handle_end_tag(self) -> None:
        if not self._scope_stack:
            return
        scope = self._scope_stack.pop()
        if scope.opened_if:
            self._indent -= 1
        if scope.opened_for:
            self._indent -= 1

    def _emit_attr_expressions(self, attr: Attribute, tag_offset: int) -> None:
        """Check every `{expr}` inside an ordinary attribute value."""
        if attr.segments is None:
            return
        for seg in attr.segments:
            if isinstance(seg, AttrExpr):
                self._emit_expr(seg.code, tag_offset, kind="attr-expr")

    # --- emission helpers ----------------------------------------------

    def _emit_expr(self, code: str, offset: int, *, kind: str) -> None:
        wrapped = self._safe_expr(code)
        self._record_line(offset, kind)
        self._lines.append(self._ind() + f"_ = ({wrapped})")

    def _emit_typed_expr(self, code: str, offset: int, *, kind: str, typ: str) -> None:
        wrapped = self._safe_expr(code)
        self._record_line(offset, kind)
        # We don't use the result; the annotation is what makes ty check the
        # expression's type against `typ`.
        self._lines.append(
            self._ind() + f"_typed_{kind.replace('-', '_')}: {typ} = ({wrapped})"
        )

    def _safe_expr(self, code: str) -> str:
        """Return a parenthesizable Python expression source.

        If the template author wrote something that doesn't parse as a
        single expression (an empty `{}`, say), substitute `None` so the
        synthesized module still type-checks — the structural pass will
        catch the original problem separately.
        """
        code = code.strip()
        if not code:
            return "None"
        try:
            ast.parse(code, mode="eval")
        except SyntaxError:
            return "None"
        return code

    def _record_line(self, offset: int, kind: str) -> None:
        # Synth line numbers are 1-indexed; the next line we append is
        # `len(self._lines) + 1`.
        self._line_map[len(self._lines) + 1] = SourceMapEntry(
            template_offset=offset, kind=kind
        )

    def _ind(self) -> str:
        return "    " * self._indent

    # --- prelude helpers -----------------------------------------------

    def _emit_attr_params(self) -> None:
        # Keyword-only parameters: every attr is named at call sites.
        if not self._decls.attrs and not self._decls.slots:
            return
        self._lines.append("    *,")
        for attr in self._decls.attrs:
            self._lines.append(self._format_attr_param(attr))

    def _emit_slot_params(self) -> None:
        # Slots arrive as pre-rendered SafeString. `children` is the
        # default slot, exposed under that name too because some templates
        # reference it.
        slot_names = {s.name for s in self._decls.slots}
        slot_names.add("children")
        slot_names.add("default")
        for name in sorted(slot_names):
            self._lines.append(f'    {name}: SafeString = SafeString(""),')

    def _format_attr_param(self, attr: AttrDeclaration) -> str:
        # Python-keyword attr names (`class`, `for`, `if`, ...) can't appear
        # as parameter names — emit them with a trailing underscore, which
        # matches the engine's render-time alias (a template that declares
        # `class:` references it as `{class_}`).
        name = f"{attr.name}_" if keyword.iskeyword(attr.name) else attr.name
        annotation = attr.type_source
        if attr.default_source is not None:
            return f"    {name}: {annotation} = {attr.default_source},"
        return f"    {name}: {annotation},"

    def _emit_import(self, imp: ImportDeclaration) -> None:
        self._lines.append(imp.statement)

    def _inferred_module_imports(self) -> list[str]:
        """Infer `import X.Y` statements from dotted names in `attrs:` types.

        `app.users.User` needs `import app.users` for ty to resolve the
        class. Each unique dotted path (with the leaf dropped) becomes a
        module import, skipping the typing names we already provide.
        """
        modules: set[str] = set()
        all_specs: list[str] = []
        for attr in self._decls.attrs:
            all_specs.append(attr.type_source)
        for slot in self._decls.slots:
            if slot.yields_source is not None:
                all_specs.append(slot.yields_source)

        for source in all_specs:
            try:
                tree = ast.parse(source, mode="eval")
            except SyntaxError:
                continue
            for chain in _attribute_chains(tree.body):
                head = chain[0]
                if head in _BUILTIN_TYPE_NAMES:
                    continue
                if head in _PYTHON_BUILTINS:
                    continue
                if len(chain) == 1:
                    # Bare name — assume it came from an `imports:` line
                    # or is a builtin/typing name we already imported.
                    continue
                modules.add(".".join(chain[:-1]))

        return [f"import {m}" for m in sorted(modules)]


@dataclass
class _Scope:
    """One element nesting level in the synthesized walk."""

    opened_for: bool
    opened_if: bool
    tag: str


def _attribute_chains(node: ast.AST) -> list[list[str]]:
    """Collect dotted-name chains from a type expression's AST.

    `app.users.User` → [["app", "users", "User"]]
    `list[app.users.User]` → [["list"], ["app", "users", "User"]]
    """
    chains: list[list[str]] = []

    def visit(n: ast.AST) -> None:
        match n:
            case ast.Name(id=name):
                chains.append([name])
            case ast.Attribute():
                chain = dotted_chain(n)
                if chain is not None:
                    chains.append(chain)
                else:
                    ast.iter_fields(n)
                    for child in ast.iter_child_nodes(n):
                        visit(child)
            case _:
                for child in ast.iter_child_nodes(n):
                    visit(child)

    visit(node)
    return chains


def _single_expr_value(attr: Attribute) -> str | None:
    """For `:if={code}` / `:for={code}` — return the expression code or None."""
    if attr.segments is None or len(attr.segments) != 1:
        return None
    seg = attr.segments[0]
    if isinstance(seg, AttrExpr):
        return seg.code
    return None


_PYTHON_BUILTINS = frozenset(
    {
        "int",
        "str",
        "bool",
        "float",
        "bytes",
        "list",
        "dict",
        "set",
        "tuple",
        "frozenset",
        "None",
        "True",
        "False",
        "object",
        "type",
        "Exception",
    }
)
