from __future__ import annotations

from collections.abc import Generator
from datetime import datetime
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from typing import Self


from plain.logs import get_framework_logger
from plain.postgres.ddl import compile_database_default_sql
from plain.postgres.dialect import quote_name
from plain.postgres.expressions import DatabaseDefaultExpression
from plain.postgres.fields import (
    BinaryField,
    DateField,
    DateTimeField,
    Field,
    TimeField,
)
from plain.postgres.fields.related import RelatedField
from plain.postgres.fields.reverse_related import ManyToManyRel
from plain.postgres.transaction import atomic
from plain.utils import timezone

if TYPE_CHECKING:
    from plain.postgres.base import Model
    from plain.postgres.connection import DatabaseConnection
    from plain.postgres.fields import Field

logger = get_framework_logger()


class DatabaseSchemaEditor:
    """
    Responsible for emitting schema-changing statements to PostgreSQL - model
    creation/removal/alteration, field renaming, index management, and so on.
    """

    sql_create_table = "CREATE TABLE %(table)s (%(definition)s)"
    sql_rename_table = "ALTER TABLE %(old_table)s RENAME TO %(new_table)s"
    sql_delete_table = "DROP TABLE %(table)s CASCADE"

    sql_create_column = "ALTER TABLE %(table)s ADD COLUMN %(column)s %(definition)s"
    sql_alter_column = "ALTER TABLE %(table)s %(changes)s"
    sql_alter_column_type = "ALTER COLUMN %(column)s TYPE %(type)s"
    sql_alter_column_null = "ALTER COLUMN %(column)s DROP NOT NULL"
    sql_alter_column_not_null = "ALTER COLUMN %(column)s SET NOT NULL"
    sql_alter_column_default = "ALTER COLUMN %(column)s SET DEFAULT %(default)s"
    sql_alter_column_no_default = "ALTER COLUMN %(column)s DROP DEFAULT"
    sql_delete_column = "ALTER TABLE %(table)s DROP COLUMN %(column)s CASCADE"
    sql_rename_column = (
        "ALTER TABLE %(table)s RENAME COLUMN %(old_column)s TO %(new_column)s"
    )
    # Setting all constraints to IMMEDIATE to allow changing data in the same transaction.
    sql_update_with_db_default = (
        "UPDATE %(table)s SET %(column)s = DEFAULT WHERE %(column)s IS NULL"
        "; SET CONSTRAINTS ALL IMMEDIATE"
    )
    sql_update_with_default = (
        "UPDATE %(table)s SET %(column)s = %(default)s WHERE %(column)s IS NULL"
        "; SET CONSTRAINTS ALL IMMEDIATE"
    )

    def __init__(
        self,
        connection: DatabaseConnection,
        atomic: bool = True,
        collect_sql: bool = False,
    ):
        self.connection = connection
        self.collect_sql = collect_sql
        self.atomic_migration = atomic and not collect_sql

    # State-managing methods

    def __enter__(self) -> Self:
        self.executed_sql: list[str] = []
        if self.atomic_migration:
            self.atomic = atomic()
            self.atomic.__enter__()
        return self

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        if self.atomic_migration:
            self.atomic.__exit__(exc_type, exc_value, traceback)

    # Core utility functions

    def execute(
        self, sql: str, params: tuple[Any, ...] | list[Any] | None = ()
    ) -> None:
        """Execute the given SQL statement, with optional parameters."""
        sql_str = sql

        # Merge the query client-side, as PostgreSQL won't do it server-side.
        if params is not None:
            sql_str = self.connection.compose_sql(sql_str, params)
            params = None

        # Log the command we're running, then run it
        logger.debug("Schema SQL executed", extra={"sql": sql_str, "params": params})

        # Track executed SQL for display in migration output
        self.executed_sql.append(sql_str)

        if self.collect_sql:
            return

        with self.connection.cursor() as cursor:
            cursor.execute(sql_str, params)

    def table_sql(self, model: type[Model]) -> tuple[str, list[Any]]:
        """Take a model and return its table definition."""
        column_sqls = []
        params = []
        for field in model._model_meta.local_fields:
            # SQL. Expression defaults (`default=Now()`, `default=GenRandomUUID()`)
            # persist on the column and therefore must be inlined during CREATE TABLE.
            include_default = isinstance(field.default, DatabaseDefaultExpression)
            definition, extra_params = self.column_sql(
                model, field, include_default=include_default
            )
            if definition is None:
                continue
            # Autoincrement SQL (e.g. GENERATED BY DEFAULT AS IDENTITY).
            col_type_suffix = field.db_type_suffix()
            if col_type_suffix:
                definition += f" {col_type_suffix}"
            if extra_params:
                params.extend(extra_params)
            # FK constraints are handled by convergence, not during table creation.
            # Add the SQL to our big list.
            column_sqls.append(f"{quote_name(field.column)} {definition}")
        # Constraints are not created inline — they're managed by convergence.
        sql = self.sql_create_table % {
            "table": quote_name(model.model_options.db_table),
            "definition": ", ".join(col for col in column_sqls if col),
        }
        return sql, params

    # Field <-> database mapping functions

    def _iter_column_sql(
        self,
        column_db_type: str,
        params: list[Any],
        model: type[Model],
        field: Field,
        include_default: bool,
    ) -> Generator[str]:
        yield column_db_type
        # Work out nullability.
        null = field.allow_null
        # Include a default value, if requested.
        if include_default:
            if isinstance(field.default, DatabaseDefaultExpression):
                # Expression defaults are inlined into the DDL — they render
                # as parameter-free SQL and become the column's persistent
                # DEFAULT.
                yield f"DEFAULT {self._compile_expression(field.default)}"
            else:
                default_value = self.effective_default(field)
                if default_value is not None:
                    yield "DEFAULT %s"
                    params.append(default_value)

        if not null:
            yield "NOT NULL"
        else:
            yield "NULL"

        if field.primary_key:
            yield "PRIMARY KEY"

    def column_sql(
        self, model: type[Model], field: Field, include_default: bool = False
    ) -> tuple[str | None, list[Any] | None]:
        """
        Return the column definition for a field. The field must already have
        had set_attributes_from_name() called.
        """
        # Get the column's type and use that as the basis of the SQL.
        column_db_type = field.db_type()
        # Check for fields that aren't actually columns (e.g. M2M).
        if column_db_type is None:
            return None, None
        params: list[Any] = []
        return (
            " ".join(
                # This appends to the params being returned.
                self._iter_column_sql(
                    column_db_type,
                    params,
                    model,
                    field,
                    include_default,
                )
            ),
            params,
        )

    def _compile_expression(self, expression: Any) -> str:
        """Compile a DatabaseDefaultExpression for inlining into DDL."""
        return compile_database_default_sql(expression)

    @staticmethod
    def _effective_default(field: Field) -> Any:
        # This method allows testing its logic without a connection.
        if field.has_default():
            default = field.get_default()
            if isinstance(default, DatabaseDefaultExpression):
                # Expression defaults are handled via DDL inlining, not as a
                # Python-side parameterized value.
                return None
        elif (
            not field.allow_null and not field.required and field.empty_strings_allowed
        ):
            if isinstance(field, BinaryField):
                default = b""
            else:
                default = ""
        elif getattr(field, "auto_now", False) or getattr(field, "auto_now_add", False):
            if isinstance(field, DateTimeField):
                default = timezone.now()
            else:
                default = datetime.now()
                if isinstance(field, DateField):
                    default = default.date()
                elif isinstance(field, TimeField):
                    default = default.time()
        else:
            default = None
        return default

    def effective_default(self, field: Field) -> Any:
        """Return a field's effective database default value."""
        return field.get_db_prep_save(self._effective_default(field), self.connection)

    # Actions

    def create_model(self, model: type[Model]) -> None:
        """Create a table for the given model."""
        sql, params = self.table_sql(model)
        # Prevent using [] as params, in the case a literal '%' is used in the
        # definition.
        self.execute(sql, params or None)

    def delete_model(self, model: type[Model]) -> None:
        """Delete a model from the database."""
        self.execute(
            self.sql_delete_table
            % {
                "table": quote_name(model.model_options.db_table),
            }
        )

    def alter_db_table(
        self, model: type[Model], old_db_table: str, new_db_table: str
    ) -> None:
        """Rename the table a model points to."""
        if old_db_table == new_db_table:
            return
        self.execute(
            self.sql_rename_table
            % {
                "old_table": quote_name(old_db_table),
                "new_table": quote_name(new_db_table),
            }
        )

    def add_field(self, model: type[Model], field: Field) -> None:
        """
        Create a field on a model. Usually involves adding a column, but may
        involve adding a table instead (for M2M fields).
        """
        # Get the column's definition
        definition, params = self.column_sql(model, field, include_default=True)
        # It might not actually have a column behind it
        if definition is None:
            return
        if col_type_suffix := field.db_type_suffix():
            definition += f" {col_type_suffix}"
        # FK constraints are handled by convergence, not inline during add_field.
        # Build the SQL and run it
        sql = self.sql_create_column % {
            "table": quote_name(model.model_options.db_table),
            "column": quote_name(field.column),
            "definition": definition,
        }
        self.execute(sql, params)
        # Drop the default if we need to
        # (Plain usually does not use in-database defaults — except for
        # DatabaseDefaultExpression defaults, which PERSIST on the column.)
        if (
            not isinstance(field.default, DatabaseDefaultExpression)
            and self.effective_default(field) is not None
        ):
            changes_sql, params = self._alter_column_default_sql(
                model, None, field, drop=True
            )
            sql = self.sql_alter_column % {
                "table": quote_name(model.model_options.db_table),
                "changes": changes_sql,
            }
            self.execute(sql, params)

    def remove_field(self, model: type[Model], field: Field) -> None:
        """
        Remove a field from a model. Usually involves deleting a column,
        but for M2Ms may involve deleting a table.
        """
        # It might not actually have a column behind it
        if field.db_type() is None:
            return
        # FK constraints are dropped automatically by CASCADE on DROP COLUMN.
        # Delete the column
        sql = self.sql_delete_column % {
            "table": quote_name(model.model_options.db_table),
            "column": quote_name(field.column),
        }
        self.execute(sql)

    def alter_field(
        self,
        model: type[Model],
        old_field: Field,
        new_field: Field,
    ) -> None:
        """
        Allow a field's type, uniqueness, nullability, default, column,
        constraints, etc. to be modified.
        `old_field` is required to compute the necessary changes.
        """
        if not self._field_should_be_altered(old_field, new_field):
            return
        # Ensure this field is even column-based
        old_type = old_field.db_type()
        new_type = new_field.db_type()
        if (old_type is None and not isinstance(old_field, RelatedField)) or (
            new_type is None and not isinstance(new_field, RelatedField)
        ):
            raise ValueError(
                f"Cannot alter field {old_field} into {new_field} - they do not properly define "
                "db_type (are you using a badly-written custom field?)",
            )
        elif (
            old_type is None
            and new_type is None
            and isinstance(old_field, RelatedField)
            and isinstance(old_field.remote_field, ManyToManyRel)
            and isinstance(new_field, RelatedField)
            and isinstance(new_field.remote_field, ManyToManyRel)
        ):
            # Both sides have through models; this is a no-op.
            return
        elif old_type is None or new_type is None:
            raise ValueError(
                f"Cannot alter field {old_field} into {new_field} - they are not compatible types "
                "(you cannot alter to or from M2M fields, or add or remove "
                "through= on M2M fields)"
            )

        self._alter_field(
            model,
            old_field,
            new_field,
            old_type,
            new_type,
        )

    def _field_data_type(self, field: Field) -> str | None:
        if isinstance(field, RelatedField):
            return field.rel_db_type()
        if field.db_type_sql is not None:
            return field.db_type_sql
        return field.db_type()

    def _alter_field(
        self,
        model: type[Model],
        old_field: Field,
        new_field: Field,
        old_type: str,
        new_type: str,
    ) -> None:
        """Perform a "physical" (non-ManyToMany) field update."""
        # Guard: introducing an expression default at the same time as a
        # nullable→NOT NULL transition would require backfilling existing
        # NULL rows by evaluating the expression. effective_default() returns
        # None for expression defaults (they're inlined into DDL, not
        # parameterized), so the existing 4-step dance would UPDATE NULL rows
        # with NULL and then fail SET NOT NULL. Handling this cleanly belongs
        # to convergence-era work; for now, require the user to split it into
        # two migrations. (If the expression default was already on the column
        # before this migration, the column has no NULLs and SET NOT NULL is
        # safe — that path is allowed.)
        if (
            old_field.allow_null
            and not new_field.allow_null
            and isinstance(new_field.default, DatabaseDefaultExpression)
            and not isinstance(old_field.default, DatabaseDefaultExpression)
        ):
            raise NotImplementedError(
                f"Cannot alter {model.__name__}.{new_field.name} to NOT NULL "
                f"and add an expression default ({new_field.default!r}) in the "
                "same migration. Add the expression default in one migration, "
                "then change to NOT NULL in a follow-up."
            )
        # FK constraints are managed by convergence, not the schema editor.
        # Have they renamed the column?
        if old_field.column != new_field.column:
            self.execute(
                self._rename_field_sql(
                    model.model_options.db_table, old_field, new_field, new_type
                )
            )
        # If the column already carries an expression DEFAULT and we're about
        # to change its type, drop the DEFAULT first — Postgres rejects
        # ALTER COLUMN TYPE when the existing DEFAULT can't cast to the new
        # type. Done after the rename so the column name in the DDL is
        # consistent with the live schema. The end-of-_alter_field
        # reconciliation below will re-issue SET DEFAULT for the new field
        # if it still has an expression default.
        if (
            isinstance(old_field.default, DatabaseDefaultExpression)
            and old_field.db_type() != new_field.db_type()
        ):
            drop_sql, _ = self._alter_column_default_sql(
                model, old_field, new_field, drop=True
            )
            self.execute(
                self.sql_alter_column
                % {
                    "table": quote_name(model.model_options.db_table),
                    "changes": drop_sql,
                }
            )
        # Next, start accumulating actions to do
        actions = []
        null_actions = []
        post_actions = []
        # Type suffix change? (e.g. auto increment).
        old_type_suffix = old_field.db_type_suffix()
        new_type_suffix = new_field.db_type_suffix()
        # Type change?
        if old_type != new_type or old_type_suffix != new_type_suffix:
            fragment, other_actions = self._alter_column_type_sql(
                model, old_field, new_field, new_type
            )
            actions.append(fragment)
            post_actions.extend(other_actions)
        # When changing a column NULL constraint to NOT NULL with a given
        # default value, we need to perform 4 steps:
        #  1. Add a default for new incoming writes
        #  2. Update existing NULL rows with new default
        #  3. Replace NULL constraint with NOT NULL
        #  4. Drop the default again.
        # Default change?
        needs_database_default = False
        if old_field.allow_null and not new_field.allow_null:
            old_default = self.effective_default(old_field)
            new_default = self.effective_default(new_field)
            if old_default != new_default and new_default is not None:
                needs_database_default = True
                actions.append(
                    self._alter_column_default_sql(model, old_field, new_field)
                )
        # Nullability change?
        if old_field.allow_null != new_field.allow_null:
            fragment = self._alter_column_null_sql(model, old_field, new_field)
            if fragment:
                null_actions.append(fragment)
        # Only if we have a default and there is a change from NULL to NOT NULL
        four_way_default_alteration = new_field.has_default() and (
            old_field.allow_null and not new_field.allow_null
        )
        if actions or null_actions:
            if not four_way_default_alteration:
                # If we don't have to do a 4-way default alteration we can
                # directly run a (NOT) NULL alteration
                actions += null_actions
            # Combine actions together
            if actions:
                sql, params = tuple(zip(*actions))
                actions = [(", ".join(sql), sum(params, []))]
            # Apply those actions
            for sql, params in actions:
                self.execute(
                    self.sql_alter_column
                    % {
                        "table": quote_name(model.model_options.db_table),
                        "changes": sql,
                    },
                    params,
                )
            if four_way_default_alteration:
                if isinstance(new_field.default, DatabaseDefaultExpression):
                    # Ensure the column's DEFAULT reflects the NEW expression
                    # before backfilling — otherwise UPDATE col = DEFAULT
                    # would use whatever the column currently has (the old
                    # default, or nothing if a type change just dropped it).
                    set_default_sql, _ = self._alter_column_default_sql(
                        model, old_field, new_field
                    )
                    self.execute(
                        self.sql_alter_column
                        % {
                            "table": quote_name(model.model_options.db_table),
                            "changes": set_default_sql,
                        }
                    )
                    # Now that the column carries the expression as its DEFAULT,
                    # tell Postgres to evaluate it for each NULL row — this
                    # is the only way to get per-row evaluation of a volatile
                    # function.
                    self.execute(
                        self.sql_update_with_db_default
                        % {
                            "table": quote_name(model.model_options.db_table),
                            "column": quote_name(new_field.column),
                        }
                    )
                else:
                    # Update existing rows with default value
                    self.execute(
                        self.sql_update_with_default
                        % {
                            "table": quote_name(model.model_options.db_table),
                            "column": quote_name(new_field.column),
                            "default": "%s",
                        },
                        [new_default],
                    )
                # Since we didn't run a NOT NULL change before we need to do it
                # now
                for sql, params in null_actions:
                    self.execute(
                        self.sql_alter_column
                        % {
                            "table": quote_name(model.model_options.db_table),
                            "changes": sql,
                        },
                        params,
                    )
        if post_actions:
            for sql, params in post_actions:
                self.execute(sql, params)
        # Drop the default if we need to
        # (Plain usually does not use in-database defaults)
        if needs_database_default:
            changes_sql, params = self._alter_column_default_sql(
                model, old_field, new_field, drop=True
            )
            sql = self.sql_alter_column % {
                "table": quote_name(model.model_options.db_table),
                "changes": changes_sql,
            }
            self.execute(sql, params)

    def _alter_column_null_sql(
        self, model: type[Model], old_field: Field, new_field: Field
    ) -> tuple[str, list[Any]]:
        """
        Return a (sql, params) fragment to set a column to null or non-null
        as required by new_field.
        """
        sql = (
            self.sql_alter_column_null
            if new_field.allow_null
            else self.sql_alter_column_not_null
        )
        return (
            sql
            % {
                "column": quote_name(new_field.column),
                "type": new_field.db_type(),
            },
            [],
        )

    def _alter_column_default_sql(
        self,
        model: type[Model],
        old_field: Field | None,
        new_field: Field,
        drop: bool = False,
    ) -> tuple[str, list[Any]]:
        """
        Return a (sql, params) fragment to add or drop (depending on the drop
        argument) a default to new_field's column.
        """
        if drop:
            return (
                self.sql_alter_column_no_default
                % {
                    "column": quote_name(new_field.column),
                    "type": new_field.db_type(),
                },
                [],
            )

        if isinstance(new_field.default, DatabaseDefaultExpression):
            # Inline the compiled expression into the DDL; no params.
            default_sql = self._compile_expression(new_field.default)
            return (
                self.sql_alter_column_default
                % {
                    "column": quote_name(new_field.column),
                    "type": new_field.db_type(),
                    "default": default_sql,
                },
                [],
            )

        new_default = self.effective_default(new_field)
        return (
            self.sql_alter_column_default
            % {
                "column": quote_name(new_field.column),
                "type": new_field.db_type(),
                "default": "%s",
            },
            [new_default],
        )

    def _alter_column_type_sql(
        self,
        model: type[Model],
        old_field: Field,
        new_field: Field,
        new_type: str,
    ) -> tuple[tuple[str, list[Any]], list[tuple[str, list[Any]]]]:
        """
        Return a two-tuple of: an SQL fragment of (sql, params) to insert into
        an ALTER TABLE statement and a list of extra (sql, params) tuples to
        run once the field is altered.
        """
        self.sql_alter_column_type = "ALTER COLUMN %(column)s TYPE %(type)s"
        # Cast when data type changed.
        if self._field_data_type(old_field) != self._field_data_type(new_field):
            self.sql_alter_column_type += " USING %(column)s::%(type)s"
        return (
            (
                self.sql_alter_column_type
                % {
                    "column": quote_name(new_field.column),
                    "type": new_type,
                },
                [],
            ),
            [],
        )

    def _field_should_be_altered(
        self, old_field: Field, new_field: Field, ignore: set[str] | None = None
    ) -> bool:
        ignore = ignore or set()
        _, old_path, old_args, old_kwargs = old_field.deconstruct()
        _, new_path, new_args, new_kwargs = new_field.deconstruct()
        # Don't alter when:
        # - changing only a field name
        # - changing an attribute that doesn't affect the schema
        # - changing an attribute in the provided set of ignored attributes
        for attr in ignore.union(old_field.non_db_attrs):
            old_kwargs.pop(attr, None)
        for attr in ignore.union(new_field.non_db_attrs):
            new_kwargs.pop(attr, None)
        return quote_name(old_field.column) != quote_name(new_field.column) or (
            old_path,
            old_args,
            old_kwargs,
        ) != (new_path, new_args, new_kwargs)

    def _rename_field_sql(
        self, table: str, old_field: Field, new_field: Field, new_type: str
    ) -> str:
        return self.sql_rename_column % {
            "table": quote_name(table),
            "old_column": quote_name(old_field.column),
            "new_column": quote_name(new_field.column),
            "type": new_type,
        }
