# Generated by Plain 0.52.2 on 2025-07-08 01:17

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedItem",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("key", postgres.TextField(max_length=255)),
                ("value", postgres.JSONField(allow_null=True, required=False)),
                ("expires_at", postgres.DateTimeField(allow_null=True, required=False)),
                ("created_at", postgres.DateTimeField(auto_now_add=True)),
                ("updated_at", postgres.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="cacheditem",
            index=postgres.Index(
                fields=["expires_at"], name="plaincache__expires_5a9119_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cacheditem",
            constraint=postgres.UniqueConstraint(
                fields=("key",), name="plaincache_cacheditem_unique_key"
            ),
        ),
    ]
