# Generated by Plain 0.52.2 on 2025-07-08 01:17

from plain import models
from plain.models import fields, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedItem",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("key", fields.CharField(max_length=255)),
                ("value", fields.JSONField(allow_null=True, required=False)),
                ("expires_at", fields.DateTimeField(allow_null=True, required=False)),
                ("created_at", fields.DateTimeField(auto_now_add=True)),
                ("updated_at", fields.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="cacheditem",
            index=models.Index(
                fields=["expires_at"], name="plaincache__expires_5a9119_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cacheditem",
            constraint=models.UniqueConstraint(
                fields=("key",), name="plaincache_cacheditem_unique_key"
            ),
        ),
    ]
