# Generated by Plain 5.0.dev20231127233940 on 2023-12-22 17:40

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plaincache", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CacheItem",
            new_name="CachedItem",
        ),
    ]
