# Generated by Bolt 5.0.dev20231229213240 on 2023-12-29 22:04

from bolt.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boltqueue", "0005_remove_jobresult_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobresult",
            old_name="completed_at",
            new_name="ended_at",
        ),
    ]
