# Generated by Plain 5.0.dev20240121220125 on 2024-01-22 16:53

from bolt.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boltqueue", "0015_job_worker_uuid_jobresult_worker_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="worker_uuid",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="worker_uuid",
        ),
    ]
