# Generated by Plain 0.94.0 on 2025-12-13 23:47

import uuid
from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="S3File",
            fields=[
                ("id", models.PrimaryKeyField()),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("key", models.CharField(max_length=500)),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64, required=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="s3file",
            index=models.Index(fields=["uuid"], name="plains3_s3f_uuid_f52e97_idx"),
        ),
        migrations.AddIndex(
            model_name="s3file",
            index=models.Index(fields=["key"], name="plains3_s3f_key_a488eb_idx"),
        ),
        migrations.AddIndex(
            model_name="s3file",
            index=models.Index(
                fields=["created_at"], name="plains3_s3f_created_76240a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="s3file",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="plains3_s3file_unique_uuid"
            ),
        ),
    ]
