model: o1-preview
editor-model: o1-preview
weak-model: o1-mini
map-tokens: 8192
input-history-file: .github/ottobot/.cache/.aider.input.history
chat-history-file: .github/ottobot/.cache/.aider.chat.history.md
commit-prompt: |
  You are an expert software engineer that generates concise, \
  one-line Git commit messages based on the provided diffs.
  Review the provided context and diffs which are about to be committed to a git repo.
  Review the diffs carefully.
  Generate a one-line commit message for those changes.

  Ensure the commit message:
  - Is in the imperative mood (e.g., \"Add feature\" not \"Added feature\" or \"Adding feature\").
  - Does not exceed 72 characters.

  Reply only with the one-line commit message, without any additional text, explanations, \
  or line breaks.
