import collections.abc
import copy
import enum
from collections.abc import Callable, Iterable, Sequence
from functools import cached_property
from typing import (
    TYPE_CHECKING,
    Any,
    Self,
    cast,
    overload,
)

from plain.postgres.constants import LOOKUP_SEP
from plain.postgres.dialect import quote_name
from plain.postgres.enums import ChoicesMeta
from plain.postgres.query_utils import Q, RegisterLookupMixin
from plain.postgres.selectable import Selectable
from plain.preflight import PreflightResult
from plain.utils.datastructures import DictWrapper
from plain.utils.functional import Promise
from plain.utils.itercompat import is_iterable

from plain import exceptions, validators

from ..registry import models_registry

if TYPE_CHECKING:
    from plain.postgres.base import Model
    from plain.postgres.connection import DatabaseConnection
    from plain.postgres.expressions import Col, Combinable, Func
    from plain.postgres.fields.reverse_related import ForeignObjectRel
    from plain.postgres.sql.compiler import SQLCompiler


class NOT_PROVIDED:
    pass


class DatabaseDefault:
    """Sentinel assigned to a field attribute when the column's persistent
    DEFAULT (e.g. `create_now=True`, `generate=True`) should produce the
    value on the next INSERT. The INSERT compiler recognizes the sentinel
    and emits `DEFAULT` in the VALUES clause; RETURNING then populates the
    real value back onto the instance."""

    def __repr__(self) -> str:
        return "<DatabaseDefault>"

    def __str__(self) -> str:
        return "<DatabaseDefault>"

    def __reduce__(self) -> tuple[Any, tuple]:
        # Pickling/unpickling must round-trip to the same singleton instance;
        # downstream code uses `value is DATABASE_DEFAULT` identity checks.
        return (_get_database_default_singleton, ())


DATABASE_DEFAULT = DatabaseDefault()


def _get_database_default_singleton() -> DatabaseDefault:
    return DATABASE_DEFAULT


# The values to use for "blank" in SelectFields. Will be appended to the start
# of most "choices" lists.
BLANK_CHOICE_DASH = [("", "---------")]


def _load_field(
    package_label: str, model_name: str, field_name: str
) -> Field[Any] | ForeignObjectRel:
    return models_registry.get_model(package_label, model_name)._model_meta.get_field(
        field_name
    )


# A guide to Field parameters:
#
#   * name:      The name of the field specified in the model. This is also the
#                attribute and instance __dict__ key for the field's value -- a
#                foreign key stores its raw key under the field name and is
#                reached through its descriptor.
#   * column:    The database column for this field. The same as "name",
#                except for ForeignKeys, where the "_id" suffix is appended.


def _empty(of_cls: type) -> Any:
    """Build an initialized-but-unpopulated instance of `of_cls`.

    Module-level (not a lambda or a method) because `__reduce__` names it as
    the pickle reconstructor.
    """
    return object.__new__(of_cls)


# Ordering conditions: the ones a None operand is meaningless for.
_ORDERING_SUFFIXES = frozenset({"gt", "gte", "lt", "lte"})

# The two lookups `.is_in()` can build: `any_of` for a collection of values,
# `in` for a queryset. Both take a collection, so both need the string guard.
_IS_IN_SUFFIXES = frozenset({"in", "any_of"})


class Field[T](Selectable[T], RegisterLookupMixin):
    """Base class for all field types"""

    # SQL type for this field (e.g. "text", "integer", "boolean").
    # String templates are interpolated against db_type_parameters().
    # Subclasses that need dynamic logic override db_type() instead.
    db_type_sql: str | None = None
    # Column definition suffix (e.g. "GENERATED BY DEFAULT AS IDENTITY").
    db_type_suffix_sql: str | None = None
    # SQL type for Cast() expressions. Falls back to db_type() if None.
    cast_db_type_sql: str | None = None

    # Instance attributes set during field lifecycle
    # Set by __init__; becomes the real field name once contributed to a
    # model class (set_attributes_from_name, called by contribute_to_class)
    name: str
    # Set by set_attributes_from_name (called by contribute_to_class)
    column: str
    # Set by contribute_to_class
    model: type[Model]

    # Designates whether empty strings fundamentally are allowed at the
    # database level.
    empty_strings_allowed = True
    empty_values = tuple(validators.EMPTY_VALUES)

    default_validators: tuple[
        Callable[[Any], None], ...
    ] = ()  # Default set of validators
    unique_error_message = "A %(model_name)s with this %(field_label)s already exists."

    # Kwargs that don't affect the column definition; the schema editor
    # ignores these when deciding whether an ALTER is needed. Subclasses
    # that introduce additional non-db kwargs extend this tuple.
    non_migration_attrs: tuple[str, ...] = ()

    def __init__(self) -> None:
        self.name = ""  # Set by set_attributes_from_name
        self.primary_key = False
        self.auto_created = False

    def __str__(self) -> str:
        """
        Return "package_label.model_label.field_name" for fields attached to
        models.
        """
        if self.is_lookup_reference:
            return f"{self.name} (lookup reference)"
        if not hasattr(self, "model"):
            return super().__str__()
        model = self.model
        return f"{model.model_options.label}.{self.name}"

    def __repr__(self) -> str:
        """Display the module, class, and name of the field."""
        path = f"{self.__class__.__module__}.{self.__class__.__qualname__}"
        name = getattr(self, "name", "")
        if self.is_lookup_reference:
            return f"<{path} lookup reference: {name}>"
        if name:
            return f"<{path}: {name}>"
        return f"<{path}>"

    # Typed query conditions. Available on every field; subclasses extend
    # with type-specific lookups (comparison on numeric, string ops on text).
    # The names are listed once in CONDITION_METHODS below -- anything that
    # needs the set (traversal advice, tests) imports it rather than retyping.
    # The comparisons take a value, another column of the same value type, or
    # an expression. `Field[T]` is what makes `retry_attempt.lt(retries)` the
    # typed spelling of `filter(retry_attempt__lt=F("retries"))` -- and, being
    # parameterized by the same `T`, it rejects a column of another type.
    #
    # `Field[T | None]` is the second arm because `Field` is invariant in `T`,
    # so a nullable column is a different type to the checker and a non-null
    # one wouldn't otherwise accept it. Only that direction is expressible:
    # from a nullable left there is no way to name `T` without its `None`, so
    # `note.equals(name)` is rejected while `name.equals(note)` is accepted.
    #
    # `Combinable` is deliberately unconstrained: an expression's output type
    # isn't tracked, so `priority.lt(F("name"))` type-checks. `F()` is the
    # untyped escape hatch here exactly as it is in `filter()`, and narrowing
    # it would mean typing expressions first.
    def equals(self, value: T | Field[T] | Field[T | None] | Combinable) -> Q:
        return self._build_q("equals", "", value)

    def not_equal(self, value: T | Field[T] | Field[T | None] | Combinable) -> Q:
        return ~self._build_q("not_equal", "", value)

    def gt(self, value: T | Field[T] | Field[T | None] | Combinable) -> Q:
        return self._build_q("gt", "gt", value)

    def gte(self, value: T | Field[T] | Field[T | None] | Combinable) -> Q:
        return self._build_q("gte", "gte", value)

    def lt(self, value: T | Field[T] | Field[T | None] | Combinable) -> Q:
        return self._build_q("lt", "lt", value)

    def lte(self, value: T | Field[T] | Field[T | None] | Combinable) -> Q:
        return self._build_q("lte", "lte", value)

    def is_null(self, value: bool = True) -> Q:
        return self._build_q("is_null", "isnull", value)

    def is_in(self, values: Iterable[T]) -> Q:
        """Match rows whose value is one of `values`.

        A plain collection binds as a single array parameter --
        `"col" = ANY(%s::text[])` -- so the statement has the same shape for
        any number of values, an empty list included. A queryset stays a
        subquery: `"col" IN (SELECT ...)`.

        A None in the collection raises `ValueError`: NULL is not a value a
        comparison can match, so it belongs in `is_null()`, not here.
        """
        from plain.postgres.query import QuerySet
        from plain.postgres.sql.query import Query

        if isinstance(values, QuerySet | Query):
            return self._build_q("is_in", "in", values)
        return self._build_q("is_in", "any_of", values)

    # Pattern conditions. They live on Field, like every other condition, so
    # they survive the `Field[T]` annotation models carry -- a field's declared
    # type is `Field[str]`, not `TextField[str]`, so the checker only ever sees
    # what `Field` offers. The `self` annotation is the restriction: a
    # `Field[int]` rejects `.startswith(...)` statically, and `_build_q`
    # rejects it at runtime for anything that doesn't register the lookup.
    #
    # (`JSONField` does register a jsonb `contains`, so `Field[dict].contains`
    # is rejected by the `self` type rather than at runtime -- the same
    # type-first guard the encrypted fields use.)
    def contains(self: Field[str] | Field[str | None], value: str) -> Q:
        return self._build_q("contains", "contains", value)

    def icontains(self: Field[str] | Field[str | None], value: str) -> Q:
        return self._build_q("icontains", "icontains", value)

    def startswith(self: Field[str] | Field[str | None], value: str) -> Q:
        return self._build_q("startswith", "startswith", value)

    def endswith(self: Field[str] | Field[str | None], value: str) -> Q:
        return self._build_q("endswith", "endswith", value)

    # The case-insensitive halves. `iequals` is named for the condition it is
    # (`equals`, ignoring case) rather than for the `iexact` lookup it builds --
    # there is no `exact` condition method for it to pair with.
    def iequals(self: Field[str] | Field[str | None], value: str) -> Q:
        return self._build_q("iequals", "iexact", value)

    def istartswith(self: Field[str] | Field[str | None], value: str) -> Q:
        return self._build_q("istartswith", "istartswith", value)

    def iendswith(self: Field[str] | Field[str | None], value: str) -> Q:
        return self._build_q("iendswith", "iendswith", value)

    def _build_q(self, method: str, suffix: str, value: Any) -> Q:
        """Build a Q from a lookup suffix + value. Uses Q's positional-tuple
        constructor to bypass its reserved `_connector`/`_negated` kwargs that
        confuse the type checker on `**{name: value}` expansion.

        `method` is the condition method's own name, used only for error
        messages -- it's what the caller wrote, so it's what an error should
        name.
        """
        assert self.name, (
            "Field name must be set before building a query condition; "
            "the field must be attached to a model."
        )
        if value is None and suffix in _ORDERING_SUFFIXES:
            # On a nullable field `T` includes None, so `age.gte(None)` gets
            # past the type checker -- there is no way to subtract None from a
            # TypeVar, so `self: Field[X | None], value: X` still solves X as
            # `int | None` under both ty and pyright. Refuse here instead, at
            # the call site, rather than letting it reach the compiler as a
            # "Cannot use None as a query value" ValueError with no field in it.
            raise TypeError(
                f"{type(self).__name__} {self.name!r}: .{method}() has no "
                f"meaning for None -- a SQL comparison against NULL is never "
                f"true. Use .is_null() instead."
            )
        if suffix in _IS_IN_SUFFIXES and isinstance(value, str | bytes):
            # `Iterable[T]` is satisfied by `str` when T is `str`, and `str` is
            # a `Sequence[str]`, so there is no way to exclude it statically.
            # Left alone it iterates characters and silently matches the wrong
            # rows.
            raise TypeError(
                f"{type(self).__name__} {self.name!r}: .is_in() takes a "
                f"collection of values, not a single {type(value).__name__}. "
                f"Pass a list -- .is_in([{value!r}])."
            )
        if suffix == "any_of":
            # Materialise once, here. A set or a generator is handed straight
            # to `Q`, which is copied, hashed and repr'd on its way to the
            # compiler -- a generator would be exhausted by the first of those
            # and bind an empty array.
            value = list(value)
            if any(item is None for item in value):
                # Neither of the two things a None could mean is honest.
                # Matching it means comparing against NULL, which is never
                # true; dropping it silently changes what the caller asked
                # for, and the negation is worse -- `NOT (col = ANY(ARRAY[1,
                # NULL]))` is unknown for every row, so `~is_in([1, None])`
                # would match nothing at all. Say so instead.
                raise ValueError(
                    f"{type(self).__name__} {self.name!r}: .is_in() does not "
                    f"accept None -- a SQL comparison against NULL is never "
                    f"true, so a None in the list matches nothing and, "
                    f"negated, excludes every row. Use .is_null() instead, or "
                    f"combine the two for both: "
                    f"field.is_in([...]) | field.is_null()."
                )
        if suffix and not self.get_lookup(suffix):
            # The type checker rejects most of these already (a `Field[int]`
            # has no `.startswith`); this catches what it can't see.
            raise TypeError(
                f"{type(self).__name__} {self.name!r} does not support "
                f".{method}() -- no {suffix!r} lookup is registered for it."
            )
        other_column = value if isinstance(value, Field) else None
        if other_column is not None:
            # Comparing against another column. Everything above guards the
            # left-hand field; the right-hand one gets its own say here.
            other_column.check_usable_as_comparison_column(method)
            # `F(name)` is the reference the ORM already understands, and a
            # traversed field's `name` carries its relation prefix, so this is
            # the whole conversion.
            from plain.postgres.expressions import F

            value = F(other_column.name)
        name = f"{self.name}{LOOKUP_SEP}{suffix}" if suffix else self.name
        q = Q((name, value))
        # Which model's where() this condition belongs to, and the field that
        # built it. See `Q._condition_origins`. A column comparison records
        # both sides, so a right-hand column from another model is caught the
        # same way a left-hand one is.
        origins = set()
        if source := self.source_model:
            origins.add((source, self.name))
        if other_column is not None and (source := other_column.source_model):
            origins.add((source, other_column.name))
        if origins:
            q._condition_origins = frozenset(origins)
        return q

    def check_usable_as_comparison_column(self, method: str) -> None:
        """Hook for a field used as the *right-hand* column of a comparison.

        A no-op for an ordinary column. `EncryptedField` overrides it to
        refuse: its own block lives in `_build_q`, which only ever runs on the
        field the condition was built *from*, and the type checker can't help
        either -- `EncryptedField[str]` is a `Field[str]`, so it satisfies
        `equals`'s `Field[T]` arm like any other string column.

        `method` is the condition the caller wrote on the left-hand field, so
        a refusal can name it.
        """

    def with_lookup_prefix(self, prefix: str, source_model: type[Model]) -> Self:
        """Return a detached copy of this field whose name carries `prefix`.

        This is all where() traversal needs: `Child.parent.name` hands back the
        related model's own `name` field renamed to `parent__name`, so the
        field's own condition methods build `Q(parent__name=...)`. Nothing has
        to re-implement or rewrite the field's surface, which is why a
        traversed field offers exactly what direct access offers -- including
        an encrypted field's blocks, whose error message names the full path.

        The copy is genuinely detached: it keeps only what building a Q needs
        (its class, for the lookup registry, and its name). The attachment
        state a real field carries is dropped, so it can't pass itself off as
        a column on the related model -- `str()` would otherwise report
        `examples.DeleteParent.parent__name`, and `__reduce__` would try to
        look up an attribute that doesn't exist.

        `source_model` is the model the traversal *started* from, which is the
        one a condition built here belongs to: `Order.user.email` is a
        condition for `Order.query.where()`, not `User.query.where()`. It is
        kept separately from `model` precisely because `model` is dropped.
        """
        prefixed = copy.copy(self)
        for attached in ("model", "column", "cached_col"):
            prefixed.__dict__.pop(attached, None)
        prefixed.name = f"{prefix}{LOOKUP_SEP}{self.name}"
        prefixed.__dict__["_is_lookup_reference"] = True
        prefixed.__dict__["_source_model"] = source_model
        return prefixed

    @property
    def source_model(self) -> type[Model] | None:
        """The model a condition built from this field belongs to.

        For an attached field that is the model it was declared on. For a
        traversed copy it is the root the traversal started from, not the
        related model the column lives on. A detached field (one built for an
        aggregate, never attached) has neither, and conditions from it go
        unchecked.
        """
        if source := self.__dict__.get("_source_model"):
            return source
        return self.__dict__.get("model")

    @property
    def is_lookup_reference(self) -> bool:
        """True for a field handed back by `with_lookup_prefix` -- a reference
        to a column reached through a relation, not a column on a model."""
        return bool(self.__dict__.get("_is_lookup_reference"))

    @property
    def lookup_path(self) -> str:
        """The path this field is reached by in a lookup -- the part before the
        suffix in `Q(**{f"{field.lookup_path}__icontains": value})`.

        `"email"` for a column on the model, `"user__email"` for one reached by
        traversal (`Order.user.email`), which is why generic code that has to
        build a string lookup, an `order_by()` term or a `values()` key from a
        field reference reads this rather than assembling a path itself.

        It is the field's `name`: `with_lookup_prefix` renames a traversed copy
        to its full path precisely so the field's own condition methods build
        the right `Q`. This is the sanctioned spelling of that fact.
        """
        return self.name

    def preflight(self, **kwargs: Any) -> list[PreflightResult]:
        return [*self._check_field_name()]

    def _check_field_name(self) -> list[PreflightResult]:
        """
        Check if field name is valid, i.e. 1) does not end with an
        underscore, 2) does not contain "__" and 3) is not "id".
        """
        if self.name.endswith("_"):
            return [
                PreflightResult(
                    fix="Field names must not end with an underscore.",
                    obj=self,
                    id="fields.name_ends_with_underscore",
                )
            ]
        elif LOOKUP_SEP in self.name:
            return [
                PreflightResult(
                    fix=f'Field names must not contain "{LOOKUP_SEP}".',
                    obj=self,
                    id="fields.name_contains_lookup_separator",
                )
            ]
        elif self.name == "id":
            return [
                PreflightResult(
                    fix="'id' is a reserved word that cannot be used as a field name.",
                    obj=self,
                    id="fields.reserved_field_name_id",
                )
            ]
        else:
            return []

    def get_col(self, alias: str | None, output_field: Field | None = None) -> Col:
        if alias == self.model.model_options.db_table and (
            output_field is None or output_field == self
        ):
            return self.cached_col
        from plain.postgres.expressions import Col

        return Col(alias, self, output_field)

    @cached_property
    def cached_col(self) -> Col:
        from plain.postgres.expressions import Col

        return Col(self.model.model_options.db_table, self)

    def select_format(
        self, compiler: SQLCompiler, sql: str, params: Any
    ) -> tuple[str, Any]:
        """
        Custom format for select clauses.
        """
        return sql, params

    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]:
        """
        Return enough information to recreate the field as a 4-tuple:

         * The name of the field on the model, if contribute_to_class() has
           been run.
         * The import path of the field, including the class, e.g.
           plain.postgres.IntegerField. This should be the most portable
           version, so less specific may be better.
         * A list of positional arguments.
         * A dict of keyword arguments.

        Note that the positional or keyword arguments must contain values of
        the following types (including inner values of collection types):

         * None, bool, str, int, float, complex, set, frozenset, list, tuple,
           dict
         * UUID
         * datetime.datetime (naive), datetime.date
         * top-level classes, top-level functions - will be referenced by their
           full import path
         * Storage instances - these have their own deconstruct() method

        This is because the values here must be serialized into a text format
        (possibly new Python code, possibly JSON) and these are the only types
        with encoding handlers defined.

        There's no need to return the exact way the field was instantiated this
        time, just ensure that the resulting field is the same - prefer keyword
        arguments over positional ones, and omit parameters with their default
        values.
        """
        keywords: dict[str, Any] = {}
        path = f"{self.__class__.__module__}.{self.__class__.__qualname__}"
        # Shorten `plain.postgres.fields.<submod>.X` to `plain.postgres.X`
        # when the class is re-exported at the top-level `plain.postgres`
        # namespace. The real submodule (`plain.postgres.fields.text`) is
        # importable but the shortened form is what migration files use.
        if path.startswith("plain.postgres.fields."):
            import plain.postgres as _postgres_root

            cls_name = self.__class__.__qualname__
            if getattr(_postgres_root, cls_name, None) is self.__class__:
                path = f"plain.postgres.{cls_name}"
        return (self.name, path, [], keywords)

    def clone(self) -> Self:
        """
        Uses deconstruct() to clone a new copy of this Field.
        Will not preserve any class attachments/attribute names.
        """
        _name, _path, args, kwargs = self.deconstruct()
        return self.__class__(*args, **kwargs)

    def __deepcopy__(self, memodict: dict[int, Any]) -> Self:
        # We don't have to deepcopy very much here, since most things are not
        # intended to be altered after initial creation.
        obj = copy.copy(self)
        memodict[id(self)] = obj
        return obj

    def __copy__(self) -> Self:
        # Build the instance directly rather than calling the constructor,
        # which would hit __reduce__.
        obj = object.__new__(self.__class__)
        obj.__dict__ = self.__dict__.copy()
        return obj

    def __reduce__(
        self,
    ) -> (
        tuple[Callable[..., Any], tuple[Any, ...], dict[str, Any]]
        | tuple[Callable[..., Field[Any] | ForeignObjectRel], tuple[str, str, str]]
    ):
        """
        Pickling should return the model._model_meta.fields instance of the field,
        not a new copy of that field. So, use the app registry to load the
        model and then the field back.
        """
        model = getattr(self, "model", None)
        if model is None:
            # Fields are sometimes used without attaching them to models (for
            # example in aggregation). In this case give back a plain field
            # instance. The code below will create a new empty instance of
            # class self.__class__, then update its dict with self.__dict__
            # values - so, this is very close to normal pickle.
            state = self.__dict__.copy()
            return _empty, (self.__class__,), state
        options = model.model_options
        return _load_field, (
            options.package_label,
            options.object_name,
            self.name,
        )

    def to_python(self, value: Any) -> T | None:
        """
        Convert the input value into the expected Python data type, raising
        plain.exceptions.ValidationError if the data can't be converted.
        Return the converted value. Subclasses should override this.
        """
        return value

    def db_type_parameters(self) -> DictWrapper:
        return DictWrapper(self.__dict__, quote_name, "qn_")

    def db_type(self) -> str | None:
        """Return the database column data type for this field."""
        if self.db_type_sql is None:
            return None
        return self.db_type_sql % self.db_type_parameters()

    def unqualified_db_type(self) -> str | None:
        # Uninterpolated so that parameter-only changes (e.g. `max_length`)
        # aren't flagged as data type changes by ALTER FIELD.
        if self.db_type_sql is not None:
            return self.db_type_sql
        return self.db_type()

    def rel_db_type(self) -> str | None:
        """
        Return the data type that a related field pointing to this field should
        use. For example, this method is called by ForeignKeyField to determine its data type.
        """
        return self.db_type()

    def cast_db_type(self) -> str | None:
        """Return the data type to use in the Cast() function."""
        if self.cast_db_type_sql is not None:
            return self.cast_db_type_sql % self.db_type_parameters()
        return self.db_type()

    def db_type_suffix(self) -> str | None:
        return self.db_type_suffix_sql

    def get_db_converters(
        self, connection: DatabaseConnection
    ) -> list[Callable[..., Any]]:
        if from_db_value := getattr(self, "from_db_value", None):
            return [from_db_value]
        return []

    @property
    def db_returning(self) -> bool:
        """True when the column produces a value that RETURNING should fetch
        back (DB-expression default, identity column, etc.)."""
        return self.has_db_default()

    @property
    def auto_fills_on_save(self) -> bool:
        """True when pre_save populates the field's value at save time
        (e.g. DateTimeField(update_now=True)). full_clean skips these so the
        None-before-save doesn't fail nullability/required checks."""
        return False

    def set_attributes_from_name(self, name: str) -> None:
        self.name = self.name or name
        # The database column is the field name. A foreign key overrides this
        # method only to append the "_id" suffix to `column`.
        self.column = self.name

    def contribute_to_class(self, cls: type[Model], name: str) -> None:
        """
        Register the field with the model class it belongs to.

        Field now acts as its own descriptor - it stays on the class and handles
        __get__/__set__/__delete__ directly.
        """
        self.set_attributes_from_name(name)
        self.model = cls
        cls._model_meta.add_field(self)

        # Field is its own descriptor; make sure it is set on the class so
        # attribute access hits __get__/__set__.
        if self.column:
            setattr(cls, self.name, self)

    # Descriptor protocol implementation
    #
    # The first overload is class access on a *model-valued* field -- a foreign
    # key, nullable or not. It yields `type[T]` rather than the descriptor so
    # the related model's own typed field surface is reachable for where()
    # traversal (`Child.parent.name.equals(...)`), matching the traversal
    # `ForwardForeignKeyDescriptor.__getattr__` serves at runtime. It comes
    # first so it wins over the plain `Self` overload for FK fields; a
    # non-model T never matches it.
    @overload
    def __get__[M: Model](
        self: Field[M] | Field[M | None], instance: None, owner: type[Model]
    ) -> type[M]: ...

    @overload
    def __get__(self, instance: None, owner: type[Model]) -> Self: ...

    @overload
    def __get__(self, instance: Model, owner: type[Model]) -> T: ...

    def __get__(self, instance: Model | None, owner: type[Model]) -> Self | T:
        """
        Descriptor __get__ for attribute access.

        Class access (User.email) returns the Field descriptor itself.
        Instance access (user.email) returns the field value from instance.__dict__,
        with lazy loading support if the value is not yet loaded.
        """
        # Class access - return the Field descriptor
        if instance is None:
            return self

        # If field hasn't been contributed to a class yet (e.g., used standalone
        # as an output_field in aggregates), just return self
        if not hasattr(self, "column"):
            return self

        # Instance access - get value from instance dict
        data = instance.__dict__
        field_name = self.name

        # If value not in dict, lazy load from database. Hydrate every
        # currently-missing concrete field in one query rather than one query
        # per field accessed -- this is what makes a foreign key partial
        # instance cheap to use beyond its primary key.
        if field_name not in data:
            missing = [
                f.name for f in instance._model_meta.fields if f.name not in data
            ]
            instance.refresh_from_db(fields=missing)

        return cast(T, data.get(field_name))

    def __set__(self, instance: Model, value: T) -> None:
        """
        Descriptor __set__ for attribute assignment.

        Validates and converts the value using to_python(), then stores it
        in instance.__dict__[name].

        The parameter is typed `T` (the field's value type) so a type checker
        rejects assigning incompatible types — `row.name = 123` on a
        TextField is caught at the call site. The runtime is more permissive
        (to_python converts strings → ints etc.), but encouraging explicit
        conversion at the boundary is the better default.
        """
        # Safety check: ensure field has been properly initialized
        if not hasattr(self, "column"):
            raise AttributeError(
                f"Field {self.__class__.__name__} has not been initialized properly. "
                f"The field's contribute_to_class() has not been called yet. "
                f"This usually means the field is being used before it was added to a model class."
            )

        # Convert/validate the value. The DATABASE_DEFAULT sentinel is stored
        # as-is so the INSERT compiler can emit `DEFAULT` in the VALUES clause.
        # Use a separate local so the parameter's narrow `T` type isn't
        # widened by to_python's `T | None` return.
        stored: Any
        if value is None or value is DATABASE_DEFAULT:
            stored = value
        else:
            stored = self.to_python(value)

        # Store in instance dict
        instance.__dict__[self.name] = stored

    def __delete__(self, instance: Model) -> None:
        """
        Descriptor __delete__ for attribute deletion.

        Removes the value from instance.__dict__.
        """
        try:
            del instance.__dict__[self.name]
        except KeyError:
            raise AttributeError(
                f"{instance.__class__.__name__!r} object has no attribute {self.name!r}"
            )

    def pre_save(self, model_instance: Model, add: bool) -> T | None:
        """Return field's value just before saving."""
        return getattr(model_instance, self.name)

    def get_prep_value(self, value: Any) -> Any:
        """Perform preliminary non-db specific value checks and conversions."""
        if isinstance(value, Promise):
            value = value._proxy____cast()
        return value

    def get_db_prep_value(
        self, value: Any, connection: DatabaseConnection, prepared: bool = False
    ) -> Any:
        """
        Return field's value prepared for interacting with the database backend.

        Used by the default implementations of get_db_prep_save().
        """
        if not prepared:
            value = self.get_prep_value(value)
        return value

    def get_db_prep_save(self, value: Any, connection: DatabaseConnection) -> Any:
        """Return field's value prepared for saving into a database."""
        if hasattr(value, "as_sql"):
            return value
        return self.get_db_prep_value(value, connection=connection, prepared=False)

    # Empty-value fallback used by ColumnField.get_default for the
    # not-null + empty_strings_allowed case (Python-side Model()
    # construction). BinaryField overrides with b"".
    _default_empty_value: Any = ""

    # Set to True by validate_none_only_default for the fields that accept
    # `default=None` without storing it (UUIDField, DateTimeField,
    # ForeignKeyField, EncryptedJSONField).
    _declared_default_none: bool = False

    def has_default(self) -> bool:
        return False

    def has_declared_default(self) -> bool:
        """Whether the declaration passed ``default=`` at the call site.

        Different question from ``has_default()``, which asks whether a default
        *value* is stored: the fields validated by ``validate_none_only_default``
        accept ``default=None`` and store nothing. PEP 681 reads the call site,
        so both spellings make the field optional in the synthesized
        constructor.
        """
        return self.has_default() or self._declared_default_none

    def has_persistent_literal_default(self) -> bool:
        return False

    def has_persistent_column_default(self) -> bool:
        """Whether the column carries a DEFAULT clause that must be preserved
        (DB-expression default or literal ``default=X``)."""
        return self.db_returning or self.has_persistent_literal_default()

    def get_db_default_expression(self) -> Func | None:
        # Return the expression Postgres should evaluate on INSERT (e.g.
        # Now(), GenRandomUUID()). Subclasses opt in via type-scoped kwargs
        # (DateTimeField(create_now=True), UUIDField(generate=True)).
        return None

    def has_db_default(self) -> bool:
        return self.get_db_default_expression() is not None

    def save_form_data(self, instance: Model, data: Any) -> None:
        setattr(instance, self.name, data)

    def value_from_object(self, obj: Model) -> T | None:
        """Return the value of this field in the given model instance."""
        return getattr(obj, self.name)


# The condition methods `Field` exposes, named once. Anything that needs the
# set rather than the methods themselves -- the relation-traversal advice in
# related_typed.py, the tests that sweep the surface -- imports from here
# instead of keeping its own copy in sync.
#
# The string conditions come paired with the lookup each one builds. Almost
# every one is named for its lookup; `iequals` is the exception -- there is no
# `exact` condition method for an `iexact` to pair with -- so the pairing is
# written down rather than assumed by whatever needs it.
STRING_CONDITION_LOOKUPS = {
    "contains": "contains",
    "icontains": "icontains",
    "startswith": "startswith",
    "endswith": "endswith",
    "iequals": "iexact",
    "istartswith": "istartswith",
    "iendswith": "iendswith",
}
STRING_CONDITION_METHODS = tuple(STRING_CONDITION_LOOKUPS)
CONDITION_METHODS = (
    "equals",
    "not_equal",
    "gt",
    "gte",
    "lt",
    "lte",
    "is_null",
    "is_in",
    *STRING_CONDITION_METHODS,
)


def validate_none_only_default(
    field: Field[Any], default: Any, *, allow_null: bool
) -> None:
    """Enforce the `default=None`-or-nothing contract.

    Some fields can't express a persistent literal column DEFAULT --
    ColumnField-direct ones (UUIDField, DateTimeField, ForeignKeyField) have no
    DefaultableField machinery at all, and EncryptedJSONField's ciphertext is
    non-deterministic. They still accept `default=None` so a nullable variant
    reads as *optional* in the typed constructor: a stock type checker treats a
    field as omittable only when its definition passes `default=`. None is the
    only allowed value and it requires allow_null; the caller stores nothing,
    because a nullable column already yields None when constructed without a
    value (see ColumnField.get_default). So `default=None` is purely a typing
    affordance, and `has_persistent_literal_default()` stays False.
    """
    if default is NOT_PROVIDED:
        return
    name = type(field).__name__
    if default is not None:
        raise TypeError(
            f"{name} does not accept a persistent default. "
            "Only default=None is allowed (with allow_null=True), which "
            "makes the field optional in the constructor."
        )
    if not allow_null:
        raise TypeError(f"{name}(default=None) requires allow_null=True.")
    # Nothing stores the value, so record that the call site declared it --
    # that's what `has_declared_default()` (and the preflight check that uses
    # it) needs to know.
    field._declared_default_none = True


class ColumnField[T](Field[T]):
    """Base for fields backed by a column value (required/allow_null/validators)."""

    non_migration_attrs = (
        *Field.non_migration_attrs,
        "required",
        "validators",
        "allow_null",
    )

    def __init__(
        self,
        *,
        default: Any = NOT_PROVIDED,
        required: bool = True,
        allow_null: bool = False,
        validators: Sequence[Callable[..., Any]] = (),
    ):
        validate_none_only_default(self, default, allow_null=allow_null)
        self.required = required
        self.allow_null = allow_null
        self._validators = list(validators)
        super().__init__()

    def preflight(self, **kwargs: Any) -> list[PreflightResult]:
        return [
            *super().preflight(**kwargs),
            *self._check_null_allowed_for_primary_keys(),
            *self._check_validators(),
        ]

    def _check_null_allowed_for_primary_keys(self) -> list[PreflightResult]:
        if self.primary_key and self.allow_null:
            return [
                PreflightResult(
                    fix="Primary keys must not have allow_null=True. "
                    "Set allow_null=False on the field, or "
                    "remove primary_key=True argument.",
                    obj=self,
                    id="fields.primary_key_allows_null",
                )
            ]
        return []

    def _check_validators(self) -> list[PreflightResult]:
        errors = []
        for i, validator in enumerate(self.validators):
            if not callable(validator):
                errors.append(
                    PreflightResult(
                        fix=(
                            "All 'validators' must be callable. "
                            f"validators[{i}] ({validator!r}) isn't a function or "
                            "instance of a validator class."
                        ),
                        obj=self,
                        id="fields.invalid_validator",
                    )
                )
        return errors

    @cached_property
    def validators(self) -> list[Callable[..., Any]]:
        # Some validators can't be created at field initialization time;
        # subclasses (e.g. IntegerField) override to add range validators.
        return [*self.default_validators, *self._validators]

    def run_validators(self, value: Any) -> None:
        if value in self.empty_values:
            return
        errors = []
        for v in self.validators:
            try:
                v(value)
            except exceptions.ValidationError as e:
                errors.extend(e.error_list)
        if errors:
            raise exceptions.ValidationError(errors)

    def validate(self, value: Any, model_instance: Model) -> None:
        if value is None and not self.allow_null:
            raise exceptions.ValidationError(
                "This field cannot be null.", code="allow_null"
            )
        if self.required and value in self.empty_values:
            raise exceptions.ValidationError("This field is required.", code="required")

    def clean(self, value: Any, model_instance: Model) -> T | None:
        value = self.to_python(value)
        self.validate(value, model_instance)
        self.run_validators(value)
        return value

    def get_default(self) -> Any:
        # Python-side default used when constructing model instances without
        # an explicit value. Independent of `required` (validate() catches
        # required-but-empty separately). DefaultableField overrides to
        # honor a user-provided default.
        if not self.empty_strings_allowed or self.allow_null:
            return None
        return self._default_empty_value

    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        if self.required is not True:
            kwargs["required"] = self.required
        if self.allow_null is not False:
            kwargs["allow_null"] = self.allow_null
        if list(self._validators):
            kwargs["validators"] = list(self._validators)
        return name, path, args, kwargs


class DefaultableField[T](ColumnField[T]):
    """Base for column-backed fields that accept a user-provided ``default``."""

    non_migration_attrs = (*ColumnField.non_migration_attrs, "default")

    # Whether this field can carry a *persistent* column DEFAULT via default=.
    # Subclasses that can't (EncryptedJSONField) set this False so callers like
    # the autodetector's error guidance don't suggest a kwarg that would raise.
    # Note this is only about persistent defaults: a field with this False can
    # still accept `default=None`, which stores nothing (see
    # validate_none_only_default).
    accepts_persistent_default = True

    # Subclasses set this when their only expressible column DEFAULT is the
    # class's `_default_empty_value` ("" / b"").
    only_empty_default = False

    def __init__(
        self,
        *,
        default: Any = NOT_PROVIDED,
        required: bool = True,
        allow_null: bool = False,
        validators: Sequence[Callable[..., Any]] = (),
    ):
        if default is not NOT_PROVIDED:
            if callable(default):
                raise TypeError(
                    f"{type(self).__name__}(default=...) must be a static literal. "
                    f"For empty collections pass default={{}} or default=[]; for "
                    f"per-row generation use a DB-side expression "
                    f"(create_now=True, generate=True, RandomStringField)."
                )
            if isinstance(default, str) and "\\" in default:
                # psycopg quotes backslash-bearing strings with `E'...'` escape
                # syntax, but pg_get_expr returns the stored DEFAULT as a standard
                # `'...'` literal — the two forms don't compare lexically, so
                # convergence would flag spurious drift on every sync. Reject at
                # declaration time rather than ship a sync that never converges.
                raise ValueError(
                    f"{type(self).__name__}(default=...) must not contain a backslash."
                )
            if self.only_empty_default:
                empty = self._default_empty_value
                if default is None:
                    if not allow_null or required:
                        raise ValueError(
                            f"{type(self).__name__} with default=None must also "
                            f"set allow_null=True and required=False — the "
                            f"column must accept NULL, and required=True would "
                            f"reject the defaulted None on every save."
                        )
                # `type()` (not isinstance/==) so bytearray()/memoryview(b"")
                # can't slip through — they compare equal to b"" but don't
                # deepcopy or serialize like it.
                elif type(default) is not type(empty) or default != empty:
                    raise ValueError(
                        f"{type(self).__name__} only supports default={empty!r} — "
                        f"the empty value, used to backfill existing rows when "
                        f"the field is added to a populated table."
                    )
                elif required:
                    raise ValueError(
                        f"{type(self).__name__} with default={empty!r} must also "
                        f"set required=False — the default fills the field with "
                        f"an empty value that required=True then rejects."
                    )
        self.default = default
        super().__init__(
            required=required,
            allow_null=allow_null,
            validators=validators,
        )

    def has_default(self) -> bool:
        return self.default is not NOT_PROVIDED

    def has_persistent_literal_default(self) -> bool:
        # `None` would emit `DEFAULT NULL` which is a no-op we don't want to
        # track as drift.
        return self.has_default() and self.default is not None

    def get_default(self) -> Any:
        if not self.has_default():
            return super().get_default()
        # Deep-copy so mutable literals (default=[] / default={}) don't leak
        # shared state across instances.
        return copy.deepcopy(self.default)

    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        if self.default is not NOT_PROVIDED:
            kwargs["default"] = self.default
        return name, path, args, kwargs


class ChoicesField[T](DefaultableField[T]):
    """Base for fields that accept a ``choices=`` parameter."""

    non_migration_attrs = (*DefaultableField.non_migration_attrs, "choices")

    # An iterable of (value, display) tuples — possibly nested for optgroups —
    # or None. Stored loosely typed because the framework accepts enums,
    # lazy iterables, and other shapes that are normalized at init time.
    choices: Any

    def __init__(
        self,
        *,
        choices: Any = None,
        required: bool = True,
        allow_null: bool = False,
        default: Any = NOT_PROVIDED,
        validators: Sequence[Callable[..., Any]] = (),
    ):
        if isinstance(choices, ChoicesMeta):
            choices = choices.choices
        elif isinstance(choices, enum.EnumMeta):
            choices = [(member.value, member.name) for member in choices]
        if isinstance(choices, collections.abc.Iterator):
            choices = list(choices)
        self.choices = choices
        super().__init__(
            required=required,
            allow_null=allow_null,
            default=default,
            validators=validators,
        )

    def preflight(self, **kwargs: Any) -> list[PreflightResult]:
        return [*super().preflight(**kwargs), *self._check_choices()]

    @classmethod
    def _choices_is_value(cls, value: Any) -> bool:
        return isinstance(value, str | Promise) or not is_iterable(value)

    def _max_length_for_choices_check(self) -> int | None:
        return None

    def _check_choices(self) -> list[PreflightResult]:
        if not self.choices:
            return []

        if not is_iterable(self.choices) or isinstance(self.choices, str):
            return [
                PreflightResult(
                    fix="'choices' must be an iterable (e.g., a list or tuple).",
                    obj=self,
                    id="fields.choices_not_iterable",
                )
            ]

        max_length = self._max_length_for_choices_check()
        choice_max_length = 0
        # Expect [group_name, [value, display]]
        for choices_group in self.choices:
            try:
                group_name, group_choices = choices_group
            except TypeError, ValueError:
                # Containing non-pairs
                break
            try:
                if not all(
                    self._choices_is_value(value) and self._choices_is_value(human_name)
                    for value, human_name in group_choices
                ):
                    break
                if max_length is not None and group_choices:
                    choice_max_length = max(
                        [
                            choice_max_length,
                            *(
                                len(value)
                                for value, _ in group_choices
                                if isinstance(value, str)
                            ),
                        ]
                    )
            except TypeError, ValueError:
                # No groups, choices in the form [value, display]
                value, human_name = group_name, group_choices
                if not self._choices_is_value(value) or not self._choices_is_value(
                    human_name
                ):
                    break
                if max_length is not None and isinstance(value, str):
                    choice_max_length = max(choice_max_length, len(value))

            # Special case: choices=['ab']
            if isinstance(choices_group, str):
                break
        else:
            if max_length is not None and choice_max_length > max_length:
                return [
                    PreflightResult(
                        fix="'max_length' is too small to fit the longest value "  # noqa: UP031
                        "in 'choices' (%d characters)." % choice_max_length,
                        obj=self,
                        id="fields.max_length_too_small_for_choices",
                    ),
                ]
            return []

        return [
            PreflightResult(
                fix="'choices' must be an iterable containing "
                "(actual value, human readable name) tuples.",
                obj=self,
                id="fields.choices_invalid_format",
            )
        ]

    def validate(self, value: Any, model_instance: Model) -> None:
        if self.choices is not None and value not in self.empty_values:
            for option_key, option_value in self.choices:
                if isinstance(option_value, list | tuple):
                    # This is an optgroup, so look inside the group for
                    # options.
                    for optgroup_key, optgroup_value in option_value:
                        if value == optgroup_key:
                            return
                elif value == option_key:
                    return
            raise exceptions.ValidationError(
                "Value %(value)r is not a valid choice.",
                code="invalid_choice",
                params={"value": value},
            )
        super().validate(value, model_instance)

    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        if self.choices is not None:
            choices = self.choices
            if isinstance(choices, collections.abc.Iterable):
                choices = list(choices)
            kwargs["choices"] = choices
        return name, path, args, kwargs

    def get_choices(
        self,
        include_blank: bool = True,
        blank_choice: list[tuple[str, str]] = BLANK_CHOICE_DASH,
    ) -> list[tuple[Any, str]]:
        """Return choices with an optional blank choice included."""
        choices = list(self.choices) if self.choices is not None else []
        if include_blank:
            blank_defined = any(choice in ("", None) for choice, _ in self.flatchoices)
            if not blank_defined:
                choices = blank_choice + choices
        return choices

    @cached_property
    def flatchoices(self) -> list[tuple[Any, Any]]:
        """Flattened version of choices tuple (choices are fixed at init)."""
        if self.choices is None:
            return []
        flat = []
        for choice, value in self.choices:
            if isinstance(value, list | tuple):
                flat.extend(value)
            else:
                flat.append((choice, value))
        return flat
