from __future__ import annotations

import collections.abc
import copy
import enum
from collections.abc import Callable, Sequence
from functools import cached_property
from typing import (
    TYPE_CHECKING,
    Any,
    Self,
    cast,
    overload,
)

from plain import exceptions, validators
from plain.postgres.constants import LOOKUP_SEP
from plain.postgres.dialect import quote_name
from plain.postgres.enums import ChoicesMeta
from plain.postgres.query_utils import RegisterLookupMixin
from plain.preflight import PreflightResult
from plain.utils.datastructures import DictWrapper
from plain.utils.functional import Promise
from plain.utils.itercompat import is_iterable

from ..registry import models_registry

if TYPE_CHECKING:
    from plain.postgres.base import Model
    from plain.postgres.connection import DatabaseConnection
    from plain.postgres.expressions import Col, Func
    from plain.postgres.fields.reverse_related import ForeignObjectRel
    from plain.postgres.sql.compiler import SQLCompiler


class Empty:
    pass


class NOT_PROVIDED:
    pass


class DatabaseDefault:
    """Sentinel assigned to a field attribute when the column's persistent
    DEFAULT (e.g. `create_now=True`, `generate=True`) should produce the
    value on the next INSERT. The INSERT compiler recognizes the sentinel
    and emits `DEFAULT` in the VALUES clause; RETURNING then populates the
    real value back onto the instance."""

    def __repr__(self) -> str:
        return "<DatabaseDefault>"

    def __str__(self) -> str:
        return "<DatabaseDefault>"

    def __reduce__(self) -> tuple[Any, tuple]:
        # Pickling/unpickling must round-trip to the same singleton instance;
        # downstream code uses `value is DATABASE_DEFAULT` identity checks.
        return (_get_database_default_singleton, ())


DATABASE_DEFAULT = DatabaseDefault()


def _get_database_default_singleton() -> DatabaseDefault:
    return DATABASE_DEFAULT


# The values to use for "blank" in SelectFields. Will be appended to the start
# of most "choices" lists.
BLANK_CHOICE_DASH = [("", "---------")]


def _load_field(
    package_label: str, model_name: str, field_name: str
) -> Field[Any] | ForeignObjectRel:
    return models_registry.get_model(package_label, model_name)._model_meta.get_field(
        field_name
    )


# A guide to Field parameters:
#
#   * name:      The name of the field specified in the model.
#   * attname:   The attribute to use on the model object. This is the same as
#                "name", except in the case of ForeignKeys, where "_id" is
#                appended.
#   * column:    The database column for this field. This is the same as
#                "attname".
#
# Code that introspects values, or does other dynamic things, should use
# attname.


def _empty(of_cls: type) -> Empty:
    new = Empty()
    new.__class__ = of_cls
    return new


class Field[T](RegisterLookupMixin):
    """Base class for all field types"""

    # SQL type for this field (e.g. "text", "integer", "boolean").
    # String templates are interpolated against db_type_parameters().
    # Subclasses that need dynamic logic override db_type() instead.
    db_type_sql: str | None = None
    # Column definition suffix (e.g. "GENERATED BY DEFAULT AS IDENTITY").
    db_type_suffix_sql: str | None = None
    # SQL type for Cast() expressions. Falls back to db_type() if None.
    cast_db_type_sql: str | None = None

    # Instance attributes set during field lifecycle
    # Set by __init__
    name: str | None
    # Set by set_attributes_from_name (called by contribute_to_class)
    attname: str
    column: str
    concrete: bool
    # Set by contribute_to_class
    model: type[Model]

    # Designates whether empty strings fundamentally are allowed at the
    # database level.
    empty_strings_allowed = True
    empty_values = list(validators.EMPTY_VALUES)

    default_validators = []  # Default set of validators
    unique_error_message = "A %(model_name)s with this %(field_label)s already exists."

    # Kwargs that don't affect the column definition; the schema editor
    # ignores these when deciding whether an ALTER is needed. Subclasses
    # that introduce additional non-db kwargs extend this tuple.
    non_migration_attrs: tuple[str, ...] = ()

    def __init__(self) -> None:
        self.name = None  # Set by set_attributes_from_name
        self.primary_key = False
        self.auto_created = False

    def __str__(self) -> str:
        """
        Return "package_label.model_label.field_name" for fields attached to
        models.
        """
        if not hasattr(self, "model"):
            return super().__str__()
        model = self.model
        return f"{model.model_options.label}.{self.name}"

    def __repr__(self) -> str:
        """Display the module, class, and name of the field."""
        path = f"{self.__class__.__module__}.{self.__class__.__qualname__}"
        name = getattr(self, "name", None)
        if name is not None:
            return f"<{path}: {name}>"
        return f"<{path}>"

    def preflight(self, **kwargs: Any) -> list[PreflightResult]:
        return [*self._check_field_name()]

    def _check_field_name(self) -> list[PreflightResult]:
        """
        Check if field name is valid, i.e. 1) does not end with an
        underscore, 2) does not contain "__" and 3) is not "id".
        """
        assert self.name is not None, "Field name must be set before checking"
        if self.name.endswith("_"):
            return [
                PreflightResult(
                    fix="Field names must not end with an underscore.",
                    obj=self,
                    id="fields.name_ends_with_underscore",
                )
            ]
        elif LOOKUP_SEP in self.name:
            return [
                PreflightResult(
                    fix=f'Field names must not contain "{LOOKUP_SEP}".',
                    obj=self,
                    id="fields.name_contains_lookup_separator",
                )
            ]
        elif self.name == "id":
            return [
                PreflightResult(
                    fix="'id' is a reserved word that cannot be used as a field name.",
                    obj=self,
                    id="fields.reserved_field_name_id",
                )
            ]
        else:
            return []

    def get_col(self, alias: str | None, output_field: Field | None = None) -> Col:
        if alias == self.model.model_options.db_table and (
            output_field is None or output_field == self
        ):
            return self.cached_col
        from plain.postgres.expressions import Col

        return Col(alias, self, output_field)

    @cached_property
    def cached_col(self) -> Col:
        from plain.postgres.expressions import Col

        return Col(self.model.model_options.db_table, self)

    def select_format(
        self, compiler: SQLCompiler, sql: str, params: Any
    ) -> tuple[str, Any]:
        """
        Custom format for select clauses.
        """
        return sql, params

    def deconstruct(self) -> tuple[str | None, str, list[Any], dict[str, Any]]:
        """
        Return enough information to recreate the field as a 4-tuple:

         * The name of the field on the model, if contribute_to_class() has
           been run.
         * The import path of the field, including the class, e.g.
           plain.postgres.IntegerField. This should be the most portable
           version, so less specific may be better.
         * A list of positional arguments.
         * A dict of keyword arguments.

        Note that the positional or keyword arguments must contain values of
        the following types (including inner values of collection types):

         * None, bool, str, int, float, complex, set, frozenset, list, tuple,
           dict
         * UUID
         * datetime.datetime (naive), datetime.date
         * top-level classes, top-level functions - will be referenced by their
           full import path
         * Storage instances - these have their own deconstruct() method

        This is because the values here must be serialized into a text format
        (possibly new Python code, possibly JSON) and these are the only types
        with encoding handlers defined.

        There's no need to return the exact way the field was instantiated this
        time, just ensure that the resulting field is the same - prefer keyword
        arguments over positional ones, and omit parameters with their default
        values.
        """
        keywords: dict[str, Any] = {}
        path = f"{self.__class__.__module__}.{self.__class__.__qualname__}"
        # Shorten `plain.postgres.fields.<submod>.X` to `plain.postgres.X`
        # when the class is re-exported at the top-level `plain.postgres`
        # namespace. The real submodule (`plain.postgres.fields.text`) is
        # importable but the shortened form is what migration files use.
        if path.startswith("plain.postgres.fields."):
            import plain.postgres as _postgres_root

            cls_name = self.__class__.__qualname__
            if getattr(_postgres_root, cls_name, None) is self.__class__:
                path = f"plain.postgres.{cls_name}"
        # Note: self.name can be None during migration state rendering when fields are cloned
        return (self.name, path, [], keywords)

    def clone(self) -> Self:
        """
        Uses deconstruct() to clone a new copy of this Field.
        Will not preserve any class attachments/attribute names.
        """
        name, path, args, kwargs = self.deconstruct()
        return self.__class__(*args, **kwargs)

    def __deepcopy__(self, memodict: dict[int, Any]) -> Self:
        # We don't have to deepcopy very much here, since most things are not
        # intended to be altered after initial creation.
        obj = copy.copy(self)
        memodict[id(self)] = obj
        return obj

    def __copy__(self) -> Self:
        # We need to avoid hitting __reduce__, so define this
        # slightly weird copy construct.
        obj = Empty()
        obj.__class__ = self.__class__
        obj.__dict__ = self.__dict__.copy()
        return cast(Self, obj)

    def __reduce__(
        self,
    ) -> (
        tuple[Callable[..., Any], tuple[Any, ...], dict[str, Any]]
        | tuple[Callable[..., Field[Any] | ForeignObjectRel], tuple[str, str, str]]
    ):
        """
        Pickling should return the model._model_meta.fields instance of the field,
        not a new copy of that field. So, use the app registry to load the
        model and then the field back.
        """
        model = getattr(self, "model", None)
        if model is None:
            # Fields are sometimes used without attaching them to models (for
            # example in aggregation). In this case give back a plain field
            # instance. The code below will create a new empty instance of
            # class self.__class__, then update its dict with self.__dict__
            # values - so, this is very close to normal pickle.
            state = self.__dict__.copy()
            return _empty, (self.__class__,), state
        assert self.name is not None
        options = model.model_options
        return _load_field, (
            options.package_label,
            options.object_name,
            self.name,
        )

    def to_python(self, value: Any) -> T | None:
        """
        Convert the input value into the expected Python data type, raising
        plain.exceptions.ValidationError if the data can't be converted.
        Return the converted value. Subclasses should override this.
        """
        return value

    def db_type_parameters(self) -> DictWrapper:
        return DictWrapper(self.__dict__, quote_name, "qn_")

    def db_type(self) -> str | None:
        """Return the database column data type for this field."""
        if self.db_type_sql is None:
            return None
        return self.db_type_sql % self.db_type_parameters()

    def unqualified_db_type(self) -> str | None:
        # Uninterpolated so that parameter-only changes (e.g. `max_length`)
        # aren't flagged as data type changes by ALTER FIELD.
        if self.db_type_sql is not None:
            return self.db_type_sql
        return self.db_type()

    def rel_db_type(self) -> str | None:
        """
        Return the data type that a related field pointing to this field should
        use. For example, this method is called by ForeignKeyField to determine its data type.
        """
        return self.db_type()

    def cast_db_type(self) -> str | None:
        """Return the data type to use in the Cast() function."""
        if self.cast_db_type_sql is not None:
            return self.cast_db_type_sql % self.db_type_parameters()
        return self.db_type()

    def db_type_suffix(self) -> str | None:
        return self.db_type_suffix_sql

    def get_db_converters(
        self, connection: DatabaseConnection
    ) -> list[Callable[..., Any]]:
        if from_db_value := getattr(self, "from_db_value", None):
            return [from_db_value]
        return []

    @property
    def db_returning(self) -> bool:
        """True when the column produces a value that RETURNING should fetch
        back (DB-expression default, identity column, etc.)."""
        return self.has_db_default()

    @property
    def auto_fills_on_save(self) -> bool:
        """True when pre_save populates the field's value at save time
        (e.g. DateTimeField(update_now=True)). full_clean skips these so the
        None-before-save doesn't fail nullability/required checks."""
        return False

    def set_attributes_from_name(self, name: str) -> None:
        self.name = self.name or name
        self.attname = self.get_attname()
        self.column = self.attname
        self.concrete = self.column is not None

    def contribute_to_class(self, cls: type[Model], name: str) -> None:
        """
        Register the field with the model class it belongs to.

        Field now acts as its own descriptor - it stays on the class and handles
        __get__/__set__/__delete__ directly.
        """
        self.set_attributes_from_name(name)
        self.model = cls
        cls._model_meta.add_field(self)

        # Field is its own descriptor; make sure it is set on the class so
        # attribute access hits __get__/__set__.
        if self.column:
            setattr(cls, self.attname, self)

    # Descriptor protocol implementation
    @overload
    def __get__(self, instance: None, owner: type[Model]) -> Self: ...

    @overload
    def __get__(self, instance: Model, owner: type[Model]) -> T: ...

    def __get__(self, instance: Model | None, owner: type[Model]) -> Self | T:
        """
        Descriptor __get__ for attribute access.

        Class access (User.email) returns the Field descriptor itself.
        Instance access (user.email) returns the field value from instance.__dict__,
        with lazy loading support if the value is not yet loaded.
        """
        # Class access - return the Field descriptor
        if instance is None:
            return self

        # If field hasn't been contributed to a class yet (e.g., used standalone
        # as an output_field in aggregates), just return self
        if not hasattr(self, "attname"):
            return self

        # Instance access - get value from instance dict
        data = instance.__dict__
        field_name = self.attname

        # If value not in dict, lazy load from database
        if field_name not in data:
            # Deferred field - load it from the database
            instance.refresh_from_db(fields=[field_name])

        return cast(T, data.get(field_name))

    def __set__(self, instance: Model, value: Any) -> None:
        """
        Descriptor __set__ for attribute assignment.

        Validates and converts the value using to_python(), then stores it
        in instance.__dict__[attname].
        """
        # Safety check: ensure field has been properly initialized
        if not hasattr(self, "attname"):
            raise AttributeError(
                f"Field {self.__class__.__name__} has not been initialized properly. "
                f"The field's contribute_to_class() has not been called yet. "
                f"This usually means the field is being used before it was added to a model class."
            )

        # Convert/validate the value. The DATABASE_DEFAULT sentinel is stored
        # as-is so the INSERT compiler can emit `DEFAULT` in the VALUES clause.
        if value is not None and value is not DATABASE_DEFAULT:
            value = self.to_python(value)

        # Store in instance dict
        instance.__dict__[self.attname] = value

    def __delete__(self, instance: Model) -> None:
        """
        Descriptor __delete__ for attribute deletion.

        Removes the value from instance.__dict__.
        """
        try:
            del instance.__dict__[self.attname]
        except KeyError:
            raise AttributeError(
                f"{instance.__class__.__name__!r} object has no attribute {self.attname!r}"
            )

    def get_attname(self) -> str:
        assert self.name is not None  # Field name must be set
        return self.name

    def pre_save(self, model_instance: Model, add: bool) -> T | None:
        """Return field's value just before saving."""
        return getattr(model_instance, self.attname)

    def get_prep_value(self, value: Any) -> Any:
        """Perform preliminary non-db specific value checks and conversions."""
        if isinstance(value, Promise):
            value = value._proxy____cast()
        return value

    def get_db_prep_value(
        self, value: Any, connection: DatabaseConnection, prepared: bool = False
    ) -> Any:
        """
        Return field's value prepared for interacting with the database backend.

        Used by the default implementations of get_db_prep_save().
        """
        if not prepared:
            value = self.get_prep_value(value)
        return value

    def get_db_prep_save(self, value: Any, connection: DatabaseConnection) -> Any:
        """Return field's value prepared for saving into a database."""
        if hasattr(value, "as_sql"):
            return value
        return self.get_db_prep_value(value, connection=connection, prepared=False)

    # Empty-value fallback used by ColumnField.get_default for the
    # not-null + not-required + empty_strings_allowed case (Python-side
    # Model() construction). BinaryField overrides with b"".
    _default_empty_value: Any = ""

    def has_default(self) -> bool:
        return False

    def has_persistent_literal_default(self) -> bool:
        return False

    def has_persistent_column_default(self) -> bool:
        """Whether the column carries a DEFAULT clause that must be preserved
        (DB-expression default or literal ``default=X``)."""
        return self.db_returning or self.has_persistent_literal_default()

    def get_db_default_expression(self) -> Func | None:
        # Return the expression Postgres should evaluate on INSERT (e.g.
        # Now(), GenRandomUUID()). Subclasses opt in via type-scoped kwargs
        # (DateTimeField(create_now=True), UUIDField(generate=True)).
        return None

    def has_db_default(self) -> bool:
        return self.get_db_default_expression() is not None

    def save_form_data(self, instance: Model, data: Any) -> None:
        assert self.name is not None
        setattr(instance, self.name, data)

    def value_from_object(self, obj: Model) -> T | None:
        """Return the value of this field in the given model instance."""
        return getattr(obj, self.attname)


class ColumnField[T](Field[T]):
    """Base for fields backed by a column value (required/allow_null/validators)."""

    non_migration_attrs = (
        *Field.non_migration_attrs,
        "required",
        "validators",
        "allow_null",
    )

    def __init__(
        self,
        *,
        required: bool = True,
        allow_null: bool = False,
        validators: Sequence[Callable[..., Any]] = (),
    ):
        self.required = required
        self.allow_null = allow_null
        self._validators = list(validators)
        super().__init__()

    def preflight(self, **kwargs: Any) -> list[PreflightResult]:
        return [
            *super().preflight(**kwargs),
            *self._check_null_allowed_for_primary_keys(),
            *self._check_validators(),
        ]

    def _check_null_allowed_for_primary_keys(self) -> list[PreflightResult]:
        if self.primary_key and self.allow_null:
            return [
                PreflightResult(
                    fix="Primary keys must not have allow_null=True. "
                    "Set allow_null=False on the field, or "
                    "remove primary_key=True argument.",
                    obj=self,
                    id="fields.primary_key_allows_null",
                )
            ]
        return []

    def _check_validators(self) -> list[PreflightResult]:
        errors = []
        for i, validator in enumerate(self.validators):
            if not callable(validator):
                errors.append(
                    PreflightResult(
                        fix=(
                            "All 'validators' must be callable. "
                            f"validators[{i}] ({repr(validator)}) isn't a function or "
                            "instance of a validator class."
                        ),
                        obj=self,
                        id="fields.invalid_validator",
                    )
                )
        return errors

    @cached_property
    def validators(self) -> list[Callable[..., Any]]:
        # Some validators can't be created at field initialization time;
        # subclasses (e.g. IntegerField) override to add range validators.
        return [*self.default_validators, *self._validators]

    def run_validators(self, value: Any) -> None:
        if value in self.empty_values:
            return
        errors = []
        for v in self.validators:
            try:
                v(value)
            except exceptions.ValidationError as e:
                errors.extend(e.error_list)
        if errors:
            raise exceptions.ValidationError(errors)

    def validate(self, value: Any, model_instance: Model) -> None:
        if value is None and not self.allow_null:
            raise exceptions.ValidationError(
                "This field cannot be null.", code="allow_null"
            )
        if self.required and value in self.empty_values:
            raise exceptions.ValidationError("This field is required.", code="required")

    def clean(self, value: Any, model_instance: Model) -> T | None:
        value = self.to_python(value)
        self.validate(value, model_instance)
        self.run_validators(value)
        return value

    def get_default(self) -> Any:
        # Python-side default used when constructing model instances without
        # an explicit value. Independent of `required` (validate() catches
        # required-but-empty separately). DefaultableField overrides to
        # honor a user-provided default.
        if not self.empty_strings_allowed or self.allow_null:
            return None
        return self._default_empty_value

    def deconstruct(self) -> tuple[str | None, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        if self.required is not True:
            kwargs["required"] = self.required
        if self.allow_null is not False:
            kwargs["allow_null"] = self.allow_null
        if list(self._validators):
            kwargs["validators"] = list(self._validators)
        return name, path, args, kwargs


class DefaultableField[T](ColumnField[T]):
    """Base for column-backed fields that accept a user-provided ``default``."""

    non_migration_attrs = (*ColumnField.non_migration_attrs, "default")

    def __init__(
        self,
        *,
        default: Any = NOT_PROVIDED,
        required: bool = True,
        allow_null: bool = False,
        validators: Sequence[Callable[..., Any]] = (),
    ):
        if default is not NOT_PROVIDED and callable(default):
            raise TypeError(
                f"{type(self).__name__}(default=...) must be a static literal. "
                f"For empty collections pass default={{}} or default=[]; for "
                f"per-row generation use a DB-side expression "
                f"(create_now=True, generate=True, RandomStringField)."
            )
        if default is not NOT_PROVIDED and isinstance(default, str) and "\\" in default:
            # psycopg quotes backslash-bearing strings with `E'...'` escape
            # syntax, but pg_get_expr returns the stored DEFAULT as a standard
            # `'...'` literal — the two forms don't compare lexically, so
            # convergence would flag spurious drift on every sync. Reject at
            # declaration time rather than ship a sync that never converges.
            raise ValueError(
                f"{type(self).__name__}(default=...) must not contain a backslash."
            )
        self.default = default
        super().__init__(
            required=required,
            allow_null=allow_null,
            validators=validators,
        )

    def has_default(self) -> bool:
        return self.default is not NOT_PROVIDED

    def has_persistent_literal_default(self) -> bool:
        # `None` would emit `DEFAULT NULL` which is a no-op we don't want to
        # track as drift.
        return self.has_default() and self.default is not None

    def get_default(self) -> Any:
        if not self.has_default():
            return super().get_default()
        # Deep-copy so mutable literals (default=[] / default={}) don't leak
        # shared state across instances.
        return copy.deepcopy(self.default)

    def deconstruct(self) -> tuple[str | None, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        if self.default is not NOT_PROVIDED:
            kwargs["default"] = self.default
        return name, path, args, kwargs


class ChoicesField[T](DefaultableField[T]):
    """Base for fields that accept a ``choices=`` parameter."""

    non_migration_attrs = (*DefaultableField.non_migration_attrs, "choices")

    # An iterable of (value, display) tuples — possibly nested for optgroups —
    # or None. Stored loosely typed because the framework accepts enums,
    # lazy iterables, and other shapes that are normalized at init time.
    choices: Any

    def __init__(
        self,
        *,
        choices: Any = None,
        required: bool = True,
        allow_null: bool = False,
        default: Any = NOT_PROVIDED,
        validators: Sequence[Callable[..., Any]] = (),
    ):
        if isinstance(choices, ChoicesMeta):
            choices = choices.choices
        elif isinstance(choices, enum.EnumMeta):
            choices = [(member.value, member.name) for member in choices]
        if isinstance(choices, collections.abc.Iterator):
            choices = list(choices)
        self.choices = choices
        super().__init__(
            required=required,
            allow_null=allow_null,
            default=default,
            validators=validators,
        )

    def preflight(self, **kwargs: Any) -> list[PreflightResult]:
        return [*super().preflight(**kwargs), *self._check_choices()]

    @classmethod
    def _choices_is_value(cls, value: Any) -> bool:
        return isinstance(value, str | Promise) or not is_iterable(value)

    def _max_length_for_choices_check(self) -> int | None:
        return None

    def _check_choices(self) -> list[PreflightResult]:
        if not self.choices:
            return []

        if not is_iterable(self.choices) or isinstance(self.choices, str):
            return [
                PreflightResult(
                    fix="'choices' must be an iterable (e.g., a list or tuple).",
                    obj=self,
                    id="fields.choices_not_iterable",
                )
            ]

        max_length = self._max_length_for_choices_check()
        choice_max_length = 0
        # Expect [group_name, [value, display]]
        for choices_group in self.choices:
            try:
                group_name, group_choices = choices_group
            except (TypeError, ValueError):
                # Containing non-pairs
                break
            try:
                if not all(
                    self._choices_is_value(value) and self._choices_is_value(human_name)
                    for value, human_name in group_choices
                ):
                    break
                if max_length is not None and group_choices:
                    choice_max_length = max(
                        [
                            choice_max_length,
                            *(
                                len(value)
                                for value, _ in group_choices
                                if isinstance(value, str)
                            ),
                        ]
                    )
            except (TypeError, ValueError):
                # No groups, choices in the form [value, display]
                value, human_name = group_name, group_choices
                if not self._choices_is_value(value) or not self._choices_is_value(
                    human_name
                ):
                    break
                if max_length is not None and isinstance(value, str):
                    choice_max_length = max(choice_max_length, len(value))

            # Special case: choices=['ab']
            if isinstance(choices_group, str):
                break
        else:
            if max_length is not None and choice_max_length > max_length:
                return [
                    PreflightResult(
                        fix="'max_length' is too small to fit the longest value "  # noqa: UP031
                        "in 'choices' (%d characters)." % choice_max_length,
                        obj=self,
                        id="fields.max_length_too_small_for_choices",
                    ),
                ]
            return []

        return [
            PreflightResult(
                fix="'choices' must be an iterable containing "
                "(actual value, human readable name) tuples.",
                obj=self,
                id="fields.choices_invalid_format",
            )
        ]

    def validate(self, value: Any, model_instance: Model) -> None:
        if self.choices is not None and value not in self.empty_values:
            for option_key, option_value in self.choices:
                if isinstance(option_value, list | tuple):
                    # This is an optgroup, so look inside the group for
                    # options.
                    for optgroup_key, optgroup_value in option_value:
                        if value == optgroup_key:
                            return
                elif value == option_key:
                    return
            raise exceptions.ValidationError(
                "Value %(value)r is not a valid choice.",
                code="invalid_choice",
                params={"value": value},
            )
        super().validate(value, model_instance)

    def deconstruct(self) -> tuple[str | None, str, list[Any], dict[str, Any]]:
        name, path, args, kwargs = super().deconstruct()
        if self.choices is not None:
            choices = self.choices
            if isinstance(choices, collections.abc.Iterable):
                choices = list(choices)
            kwargs["choices"] = choices
        return name, path, args, kwargs

    def get_choices(
        self,
        include_blank: bool = True,
        blank_choice: list[tuple[str, str]] = BLANK_CHOICE_DASH,
    ) -> list[tuple[Any, str]]:
        """Return choices with an optional blank choice included."""
        choices = list(self.choices) if self.choices is not None else []
        if include_blank:
            blank_defined = any(choice in ("", None) for choice, _ in self.flatchoices)
            if not blank_defined:
                choices = blank_choice + choices
        return choices

    @cached_property
    def flatchoices(self) -> list[tuple[Any, Any]]:
        """Flattened version of choices tuple (choices are fixed at init)."""
        if self.choices is None:
            return []
        flat = []
        for choice, value in self.choices:
            if isinstance(value, list | tuple):
                flat.extend(value)
            else:
                flat.append((choice, value))
        return flat
