from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

from plain import exceptions
from plain.preflight import PreflightResult

from .base import ColumnField

if TYPE_CHECKING:
    from plain.postgres.base import Model
    from plain.postgres.connection import DatabaseConnection


class PrimaryKeyField(ColumnField[int]):
    """Identity primary key — Postgres generates the value on INSERT.

    Accepts no constructor arguments: the column is always ``bigint GENERATED
    BY DEFAULT AS IDENTITY``, NOT NULL, with RETURNING populating the value
    back onto the instance after save.
    """

    db_type_sql = "bigint"
    cast_db_type_sql = "bigint"
    db_type_suffix_sql = "GENERATED BY DEFAULT AS IDENTITY"
    empty_strings_allowed = False

    def __init__(self) -> None:
        super().__init__(required=False)
        self.primary_key = True
        self.auto_created = True

    @property
    def db_returning(self) -> bool:
        return True

    def preflight(self, **kwargs: Any) -> list[PreflightResult]:
        errors = super().preflight(**kwargs)
        # `id` is the reserved PK name — Field._check_field_name rejects it
        # for every other field type.
        return [e for e in errors if e.id != "fields.reserved_field_name_id"]

    def deconstruct(self) -> tuple[str | None, str, list[Any], dict[str, Any]]:
        return (
            self.name,
            "plain.postgres.PrimaryKeyField",
            cast(list[Any], []),
            cast(dict[str, Any], {}),
        )

    def validate(self, value: Any, model_instance: Model) -> None:
        # Identity columns aren't user-validated — Postgres owns the value.
        pass

    def to_python(self, value: Any) -> int | None:
        if value is None:
            return value
        try:
            return int(value)
        except (TypeError, ValueError):
            raise exceptions.ValidationError(
                '"%(value)s" value must be an integer.',
                code="invalid",
                params={"value": value},
            )

    def get_prep_value(self, value: Any) -> Any:
        value = super().get_prep_value(value)
        if value is None:
            return None
        try:
            return int(value)
        except (TypeError, ValueError) as e:
            raise e.__class__(
                f"Field '{self.name}' expected a number but got {value!r}.",
            ) from e

    def get_db_prep_value(
        self, value: Any, connection: DatabaseConnection, prepared: bool = False
    ) -> Any:
        if not prepared:
            value = self.get_prep_value(value)
        return value

    def rel_db_type(self) -> str:
        return "bigint"
