# Generated by Plain 0.131.3 on 2026-04-10 02:28

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_user_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("body", postgres.TextField(default="", required=False)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("title", postgres.TextField(max_length=200)),
                (
                    "updated_at",
                    postgres.DateTimeField(create_now=True, update_now=True),
                ),
                (
                    "author",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        related_query_name="notes",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
