# Generated by Plain 0.13.1 on 2025-02-16 23:02

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.PrimaryKeyField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("make", "model"), name="unique_make_model"
            ),
        ),
    ]
