# Generated by Plain 0.52.2 on 2025-07-02 18:16

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0002_test_field_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteParent",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("name", migrations.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChildSetNull",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                (
                    "parent",
                    migrations.ForeignKey(
                        allow_null=True,
                        on_delete=migrations.SET_NULL,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildSetDefault",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                (
                    "parent",
                    migrations.ForeignKey(
                        default=1,
                        on_delete=migrations.SET_DEFAULT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildDoNothing",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                (
                    "parent",
                    migrations.ForeignKey(
                        on_delete=migrations.DO_NOTHING,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildCascade",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                (
                    "parent",
                    migrations.ForeignKey(
                        on_delete=migrations.CASCADE,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildRestrict",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                (
                    "parent",
                    migrations.ForeignKey(
                        on_delete=migrations.RESTRICT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildProtect",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                (
                    "parent",
                    migrations.ForeignKey(
                        on_delete=migrations.PROTECT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
    ]
