# Generated by Plain 0.52.2 on 2025-07-02 18:16

import plain.models.deletion
from plain.models import fields, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0002_test_field_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteParent",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("name", fields.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChildSetNull",
            fields=[
                ("id", fields.PrimaryKeyField()),
                (
                    "parent",
                    fields.ForeignKey(
                        allow_null=True,
                        on_delete=plain.models.deletion.SET_NULL,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildSetDefault",
            fields=[
                ("id", fields.PrimaryKeyField()),
                (
                    "parent",
                    fields.ForeignKey(
                        default=1,
                        on_delete=plain.models.deletion.SET_DEFAULT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildDoNothing",
            fields=[
                ("id", fields.PrimaryKeyField()),
                (
                    "parent",
                    fields.ForeignKey(
                        on_delete=plain.models.deletion.DO_NOTHING,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildCascade",
            fields=[
                ("id", fields.PrimaryKeyField()),
                (
                    "parent",
                    fields.ForeignKey(
                        on_delete=plain.models.deletion.CASCADE,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildRestrict",
            fields=[
                ("id", fields.PrimaryKeyField()),
                (
                    "parent",
                    fields.ForeignKey(
                        on_delete=plain.models.deletion.RESTRICT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildProtect",
            fields=[
                ("id", fields.PrimaryKeyField()),
                (
                    "parent",
                    fields.ForeignKey(
                        on_delete=plain.models.deletion.PROTECT,
                        to="examples.deleteparent",
                    ),
                ),
            ],
        ),
    ]
