# Generated by Plain 0.72.2 on 2025-10-07 18:23

import app.examples.models  # type: ignore[import-untyped]

import plain.models.deletion
from plain import models
from plain.models import fields, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0003_deleteparent_childsetnull_childsetdefault_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultQuerySetModel",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("name", fields.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MixinTestModel",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("created_at", fields.DateTimeField(auto_now_add=True)),
                ("updated_at", fields.DateTimeField(auto_now=True)),
                ("name", fields.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(app.examples.models.TimestampMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CustomQuerySetModel",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("name", fields.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CustomSpecialQuerySetModel",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("name", fields.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="childcascade",
            name="parent",
            field=fields.ForeignKey(
                on_delete=plain.models.deletion.CASCADE,
                related_name="childcascade_set",
                to="examples.deleteparent",
            ),
        ),
        migrations.AlterField(
            model_name="childsetdefault",
            name="parent",
            field=fields.ForeignKey(
                default=app.examples.models.ChildSetDefault.default_parent_id,
                on_delete=plain.models.deletion.SET_DEFAULT,
                to="examples.deleteparent",
            ),
        ),
    ]
