# Generated by Plain 0.72.2 on 2025-10-07 18:23

import app.examples.models  # type: ignore[import-untyped]

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0003_deleteparent_childsetnull_childsetdefault_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultQuerySetModel",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("name", migrations.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MixinTestModel",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("created_at", migrations.DateTimeField(auto_now_add=True)),
                ("updated_at", migrations.DateTimeField(auto_now=True)),
                ("name", migrations.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(app.examples.models.TimestampMixin, migrations.Model),
        ),
        migrations.CreateModel(
            name="CustomQuerySetModel",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("name", migrations.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CustomSpecialQuerySetModel",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("name", migrations.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="childcascade",
            name="parent",
            field=migrations.ForeignKey(
                on_delete=migrations.CASCADE,
                related_name="childcascade_set",
                to="examples.deleteparent",
            ),
        ),
        migrations.AlterField(
            model_name="childsetdefault",
            name="parent",
            field=migrations.ForeignKey(
                default=app.examples.models.ChildSetDefault.default_parent_id,
                on_delete=migrations.SET_DEFAULT,
                to="examples.deleteparent",
            ),
        ),
    ]
