# Generated by Plain 0.88.0 on 2025-11-14 19:44

import plain.models.deletion
from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0004_defaultquerysetmodel_mixintestmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.PrimaryKeyField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CarFeature",
            fields=[
                ("id", models.PrimaryKeyField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=plain.models.deletion.CASCADE, to="examples.car"
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=plain.models.deletion.CASCADE, to="examples.feature"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="features",
            field=models.ManyToManyField(
                related_name="cars",
                through="examples.CarFeature",
                to="examples.feature",
            ),
        ),
    ]
