# Generated by Plain 0.52.2 on 2025-07-17 02:27

from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trace",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("trace_id", migrations.CharField(max_length=255)),
                ("start_time", migrations.DateTimeField()),
                ("end_time", migrations.DateTimeField()),
                ("root_span_name", migrations.TextField(default="", required=False)),
                (
                    "request_id",
                    migrations.CharField(default="", max_length=255, required=False),
                ),
                (
                    "session_id",
                    migrations.CharField(default="", max_length=255, required=False),
                ),
                (
                    "user_id",
                    migrations.CharField(default="", max_length=255, required=False),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Span",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("span_id", migrations.CharField(max_length=255)),
                ("name", migrations.CharField(max_length=255)),
                ("kind", migrations.CharField(max_length=50)),
                (
                    "parent_id",
                    migrations.CharField(default="", max_length=255, required=False),
                ),
                ("start_time", migrations.DateTimeField()),
                ("end_time", migrations.DateTimeField()),
                (
                    "status",
                    migrations.CharField(default="", max_length=50, required=False),
                ),
                ("span_data", migrations.JSONField(default=dict, required=False)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="trace",
            constraint=migrations.UniqueConstraint(
                fields=("trace_id",), name="observer_unique_trace_id"
            ),
        ),
        migrations.AddField(
            model_name="span",
            name="trace",
            field=migrations.ForeignKey(
                on_delete=migrations.CASCADE,
                related_name="spans",
                to="plainobserver.trace",
            ),
        ),
        migrations.AddIndex(
            model_name="span",
            index=migrations.Index(
                fields=["trace", "span_id"], name="plainobserv_trace_i_89a97c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="span",
            index=migrations.Index(
                fields=["trace"], name="plainobserv_trace_i_84958a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="span",
            index=migrations.Index(
                fields=["start_time"], name="plainobserv_start_t_cb47a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="span",
            constraint=migrations.UniqueConstraint(
                fields=("trace", "span_id"), name="observer_unique_span_id"
            ),
        ),
    ]
