# Generated by Plain 0.52.2 on 2025-07-17 02:27

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trace",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("trace_id", postgres.TextField(max_length=255)),
                ("start_time", postgres.DateTimeField()),
                ("end_time", postgres.DateTimeField()),
                ("root_span_name", postgres.TextField(default="", required=False)),
                (
                    "request_id",
                    postgres.TextField(default="", max_length=255, required=False),
                ),
                (
                    "session_id",
                    postgres.TextField(default="", max_length=255, required=False),
                ),
                (
                    "user_id",
                    postgres.TextField(default="", max_length=255, required=False),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Span",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("span_id", postgres.TextField(max_length=255)),
                ("name", postgres.TextField(max_length=255)),
                ("kind", postgres.TextField(max_length=50)),
                (
                    "parent_id",
                    postgres.TextField(default="", max_length=255, required=False),
                ),
                ("start_time", postgres.DateTimeField()),
                ("end_time", postgres.DateTimeField()),
                (
                    "status",
                    postgres.TextField(default="", max_length=50, required=False),
                ),
                ("span_data", postgres.JSONField(default=dict, required=False)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="span",
            name="trace",
            field=postgres.ForeignKeyField(
                on_delete=plain.postgres.deletion.CASCADE,
                to="plainobserver.trace",
            ),
        ),
        migrations.AddIndex(
            model_name="span",
            index=postgres.Index(
                fields=["trace", "span_id"], name="plainobserv_trace_i_89a97c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="span",
            index=postgres.Index(
                fields=["trace"], name="plainobserv_trace_i_84958a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="span",
            index=postgres.Index(
                fields=["start_time"], name="plainobserv_start_t_cb47a3_idx"
            ),
        ),
    ]
