# Generated by Plain 0.54.1 on 2025-07-21 16:01

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="share_created_at",
            field=models.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AddField(
            model_name="trace",
            name="share_id",
            field=models.CharField(default="", max_length=32, required=False),
        ),
        migrations.AddField(
            model_name="trace",
            name="summary",
            field=models.CharField(default="", max_length=255, required=False),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(
                fields=["trace_id"], name="plainobserv_trace_i_075b48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(
                fields=["start_time"], name="plainobserv_start_t_636c80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(
                fields=["request_id"], name="plainobserv_request_d1d5b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(
                fields=["share_id"], name="plainobserv_share_i_754f3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(
                fields=["session_id"], name="plainobserv_session_350f42_idx"
            ),
        ),
    ]
