# Generated by Plain 0.56.1 on 2025-07-31 21:57

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainobserver",
            "0002_trace_share_created_at_trace_share_id_trace_summary_and_more",
        ),
    ]

    operations = []
