# Generated by Plain 0.61.0 on 2025-09-08 17:09

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0003_span_plainobserv_span_id_e7ade3_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="app_name",
            field=migrations.CharField(default="", max_length=255, required=False),
        ),
        migrations.AddField(
            model_name="trace",
            name="app_version",
            field=migrations.CharField(default="", max_length=255, required=False),
        ),
    ]
