# Generated by Plain 0.61.0 on 2025-09-08 21:12

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0004_trace_app_name_trace_app_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("timestamp", postgres.DateTimeField()),
                ("level", postgres.CharField(max_length=20)),
                ("logger", postgres.CharField(max_length=255)),
                ("message", postgres.TextField()),
                (
                    "span",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=plain.postgres.deletion.SET_NULL,
                        required=False,
                        to="plainobserver.span",
                    ),
                ),
                (
                    "trace",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="plainobserver.trace",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="log",
            index=postgres.Index(
                fields=["trace", "timestamp"], name="plainobserv_trace_i_fcfb7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=postgres.Index(
                fields=["trace", "span"], name="plainobserv_trace_i_1166af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=postgres.Index(
                fields=["timestamp"], name="plainobserv_timesta_64f0dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=postgres.Index(
                fields=["trace"], name="plainobserv_trace_i_c64ee0_idx"
            ),
        ),
    ]
