# Generated by Plain 0.61.0 on 2025-09-08 21:12

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0004_trace_app_name_trace_app_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("timestamp", postgres.DateTimeField()),
                ("level", postgres.TextField(max_length=20)),
                ("logger", postgres.TextField(max_length=255)),
                ("message", postgres.TextField()),
                (
                    "span",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=plain.postgres.deletion.SET_NULL,
                        required=False,
                        to="plainobserver.span",
                    ),
                ),
                (
                    "trace",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="plainobserver.trace",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
