# Generated by Plain 0.61.0 on 2025-09-08 21:12

import plain.models.deletion
from plain import models
from plain.models import fields, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0004_trace_app_name_trace_app_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", fields.PrimaryKeyField()),
                ("timestamp", fields.DateTimeField()),
                ("level", fields.CharField(max_length=20)),
                ("logger", fields.CharField(max_length=255)),
                ("message", fields.TextField()),
                (
                    "span",
                    fields.ForeignKey(
                        allow_null=True,
                        on_delete=plain.models.deletion.SET_NULL,
                        related_name="logs",
                        required=False,
                        to="plainobserver.span",
                    ),
                ),
                (
                    "trace",
                    fields.ForeignKey(
                        on_delete=plain.models.deletion.CASCADE,
                        related_name="logs",
                        to="plainobserver.trace",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["trace", "timestamp"], name="plainobserv_trace_i_fcfb7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["trace", "span"], name="plainobserv_trace_i_1166af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["timestamp"], name="plainobserv_timesta_64f0dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(fields=["trace"], name="plainobserv_trace_i_c64ee0_idx"),
        ),
    ]
