# Generated by Plain 0.61.0 on 2025-09-09 15:50

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0005_log_log_plainobserv_trace_i_fcfb7d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="logger",
        ),
    ]
