# Generated by Plain 0.93.0 on 2025-12-06 03:38

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0006_remove_log_logger"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="trace",
            name="plainobserv_share_i_754f3c_idx",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="share_created_at",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="share_id",
        ),
    ]
