# Generated by Plain 0.62.1 on 2025-09-10 02:06

from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0006_remove_log_logger"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="trace",
            name="plainobserv_session_350f42_idx",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="session_id",
        ),
    ]
