# Generated by Plain 0.127.2 on 2026-03-25 16:53

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0007_remove_trace_plainobserv_share_i_754f3c_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="trace",
            field=postgres.ForeignKeyField(
                on_delete=plain.postgres.deletion.CASCADE,
                to="plainobserver.trace",
            ),
        ),
        migrations.AlterField(
            model_name="span",
            name="trace",
            field=postgres.ForeignKeyField(
                on_delete=plain.postgres.deletion.CASCADE,
                to="plainobserver.trace",
            ),
        ),
    ]
