# Generated by Plain 0.127.2 on 2026-03-25 20:19

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plainobserver", "0008_remove_log_plainobserv_trace_i_c64ee0_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="log",
            new_name="plainobserver_log_trace_id_timestamp_idx",
            old_name="plainobserv_trace_i_fcfb7d_idx",
        ),
        migrations.RenameIndex(
            model_name="log",
            new_name="plainobserver_log_trace_id_span_id_idx",
            old_name="plainobserv_trace_i_1166af_idx",
        ),
        migrations.RenameIndex(
            model_name="log",
            new_name="plainobserver_log_timestamp_idx",
            old_name="plainobserv_timesta_64f0dc_idx",
        ),
        migrations.RenameIndex(
            model_name="span",
            new_name="plainobserver_span_span_id_idx",
            old_name="plainobserv_span_id_e7ade3_idx",
        ),
        migrations.RenameIndex(
            model_name="span",
            new_name="plainobserver_span_start_time_idx",
            old_name="plainobserv_start_t_cb47a3_idx",
        ),
        migrations.RenameIndex(
            model_name="trace",
            new_name="plainobserver_trace_trace_id_idx",
            old_name="plainobserv_trace_i_075b48_idx",
        ),
        migrations.RenameIndex(
            model_name="trace",
            new_name="plainobserver_trace_start_time_idx",
            old_name="plainobserv_start_t_636c80_idx",
        ),
        migrations.RenameIndex(
            model_name="trace",
            new_name="plainobserver_trace_request_id_idx",
            old_name="plainobserv_request_d1d5b2_idx",
        ),
        migrations.RenameIndex(
            model_name="trace",
            new_name="plainobserver_trace_session_id_idx",
            old_name="plainobserv_session_350f42_idx",
        ),
    ]
