# Generated by Plain 0.127.2 on 2026-03-25 22:04

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plainobserver",
            "0009_rename_plainobserv_trace_i_fcfb7d_idx_plainobserver_log_trace_id_timestamp_idx_and_more",
        ),
    ]

    operations = [
        # Drop orphan auto-index from old db_index=True default
        migrations.RunSQL('DROP INDEX IF EXISTS "plainobserver_log_span_id_15cd5df8"'),
    ]
