# Generated by Plain 0.21.5 on 2025-02-17 04:12

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("username", postgres.TextField(max_length=255)),
                ("is_admin", postgres.BooleanField(default=False)),
            ],
        ),
    ]
