#!/bin/sh -e

if [ "$1" = "--check" ]; then
    shift
    uv run plain-code check . "$@"
    echo "--> prettier --check..."
    npx prettier '**/*.md' --embedded-language-formatting off --tab-width 4 --log-level warn --check
else
    uv run plain-code fix . "$@"
    echo "--> prettier --write..."
    npx prettier '**/*.md' --embedded-language-formatting off --tab-width 4 --log-level warn --write
fi
