#!/bin/sh -e

for package in plain*;
do
    echo ""
    echo "${BOLD}Installing dependencies for $package${NORMAL}"
    cd "$package"
    uv sync
    cd ..
done

if [ ! -f .git/hooks/pre-commit ]; then
    echo ""
    echo "${BOLD}Installing git pre-commit hook${NORMAL}"
    cp scripts/pre-commit .git/hooks/pre-commit
fi
