#!/bin/sh -e
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

echo "${BOLD}Checking with plain-code${NORMAL}"
cd plain-code
uv run plain code check ..
cd ..

echo ""
echo "${BOLD}Running tests${NORMAL}"
./scripts/test

echo ""
echo "${BOLD}Compiling readmes${NORMAL}"
./scripts/compile-readmes
