#!/bin/sh -e

for package_dir in plain*; do
    cd $package_dir
    rm -rf dist
    uv build
    publish_output=$(uv publish --no-progress 2>&1)
    publish_exit_code=$?
    echo "$publish_output"
    if [ $publish_exit_code -ne 0 ]; then
        echo "$publish_output" | grep -q "already exists" || exit $publish_exit_code
    fi
    cd ..
done
