#!/bin/sh -e
cd plain
if [ "$1" = "--check" ]; then
    poetry run ruff check ..
    poetry run ruff format .. --check
else
    poetry run ruff --fix-only .. --unsafe-fixes
    poetry run ruff format ..
fi
