#!/bin/sh -e

workflow=".github/workflows/test.yml"
packages=$(grep 'PACKAGES:' "$workflow" | sed -E 's/^.*PACKAGES: *//')

if [ $# -gt 0 ] && printf '%s\n' $packages | grep -x "$1" >/dev/null; then
  packages=$1
  shift
fi

bold() {
    echo "\033[1m$1\033[0m"
}

bold "Found packages to test in $workflow: $packages"

for package in $packages;
do
    echo
    bold "Testing $package"
    cd "$package/tests"
    uv run --package "$package" --isolated pytest "$@"
    cd ../..
done

for demo in demos/*; do
    echo
    bold "Testing $demo"
    cd "$demo"
    uv run pytest "$@"
    cd ..
done
