# Generated by Plain 0.150.0 on 2026-06-19 17:38

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthApplication",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("client_id", postgres.RandomStringField(length=32)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                (
                    "name",
                    postgres.TextField(default="", max_length=255, required=False),
                ),
                ("redirect_uris", postgres.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("expires_at", postgres.DateTimeField()),
                (
                    "resource",
                    postgres.TextField(default="", max_length=2000, required=False),
                ),
                ("revoked", postgres.BooleanField(default=False)),
                (
                    "scope",
                    postgres.TextField(default="", max_length=500, required=False),
                ),
                ("token_hash", postgres.TextField(max_length=64)),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="users.user"
                    ),
                ),
                (
                    "application",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        to="plainoauthserver.oauthapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("code", postgres.RandomStringField(length=48)),
                ("code_challenge", postgres.TextField(max_length=128)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("expires_at", postgres.DateTimeField()),
                ("redirect_uri", postgres.TextField(max_length=2000)),
                (
                    "resource",
                    postgres.TextField(default="", max_length=2000, required=False),
                ),
                (
                    "scope",
                    postgres.TextField(default="", max_length=500, required=False),
                ),
                ("used", postgres.BooleanField(default=False)),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="users.user"
                    ),
                ),
                (
                    "application",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        to="plainoauthserver.oauthapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("expires_at", postgres.DateTimeField()),
                ("revoked", postgres.BooleanField(default=False)),
                ("token_hash", postgres.TextField(max_length=64)),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="users.user"
                    ),
                ),
                (
                    "access_token",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE, to="plainoauthserver.accesstoken"
                    ),
                ),
                (
                    "application",
                    postgres.ForeignKeyField(
                        on_delete=postgres.CASCADE,
                        to="plainoauthserver.oauthapplication",
                    ),
                ),
            ],
        ),
    ]
