# Generated by Plain 0.161.0 on 2026-09-03 01:48

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    dependencies = (("plainoauthserver", "0001_initial"),)

    operations = (
        migrations.AddField(
            model_name="oauthapplication",
            name="metadata_expires_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AddField(
            model_name="oauthapplication",
            name="metadata_fetched_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
    )
