# Generated by Plain 0.98.1 on 2026-01-15 03:03

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedNavItem",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("order", postgres.SmallIntegerField(default=0)),
                ("view_slug", postgres.TextField(max_length=255)),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to="users.User",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
