# Generated by Plain 0.98.1 on 2026-01-15 03:03

import plain.models.deletion
from plain import models
from plain.models import migrations
from plain.runtime import settings


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.settings_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedNavItem",
            fields=[
                ("id", models.PrimaryKeyField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.SmallIntegerField(default=0)),
                ("view_slug", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKeyField(
                        on_delete=plain.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="pinnednavitem",
            constraint=models.UniqueConstraint(
                fields=("user", "view_slug"),
                name="plainadmin_pinnednavitem_unique_user_view",
            ),
        ),
    ]
