# Generated by Plain 0.98.1 on 2026-01-15 03:03

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations
from plain.runtime import settings


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.settings_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedNavItem",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.CreatedAtField()),
                ("order", postgres.SmallIntegerField(default=0)),
                ("view_slug", postgres.CharField(max_length=255)),
                (
                    "user",
                    postgres.ForeignKeyField(
                        on_delete=plain.postgres.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="pinnednavitem",
            constraint=postgres.UniqueConstraint(
                fields=("user", "view_slug"),
                name="plainadmin_pinnednavitem_unique_user_view",
            ),
        ),
    ]
