# Generated by Plain 0.127.2 on 2026-03-25 18:28

import plain.postgres.deletion
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("plainadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinnednavitem",
            name="user",
            field=postgres.ForeignKeyField(
                on_delete=plain.postgres.deletion.CASCADE,
                to="users.User",
            ),
        ),
    ]
