# Generated by Plain 0.43.1 on 2025-05-23 21:47

from plain.postgres import migrations

from plain import postgres


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("email", postgres.EmailField()),
                ("password", postgres.TextField()),
                ("is_admin", postgres.BooleanField(default=False)),
            ],
        ),
    )
