# Generated by Plain 0.103.1 on 2026-02-02 17:21

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=postgres.DateTimeField(create_now=True),
        ),
    ]
