# Generated by Plain 0.103.1 on 2026-02-02 17:21

import plain.utils.timezone
from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=plain.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
