# Generated by Plain 0.21.5 on 2025-02-17 04:12

from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", migrations.PrimaryKeyField()),
                ("username", migrations.CharField(max_length=255)),
                ("is_admin", migrations.BooleanField(default=False)),
            ],
        ),
    ]
