# Generated by Plain 0.21.5 on 2025-02-17 04:12

from plain import models
from plain.models import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("username", models.CharField(max_length=255)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
    ]
