# Generated by Plain 0.131.1 on 2026-04-03 14:47

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=postgres.EmailField(),
        ),
    ]
