# Generated by Plain 0.131.1 on 2026-04-03 14:49

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=postgres.TextField(max_length=128, required=False),
        ),
    ]
